/* mrtm_errors.h — GENERATED by tools/gen-codes.py from 06-design/common/MrtmSwCodes.sysml
 * (MrtmSwCodes::ErrorCode). Do not edit: change the model and re-run. IEC 62304 §5.4.2, Class C. */
#ifndef MRTM_ERRORS_H
#define MRTM_ERRORS_H
#include <stdint.h>

/* Stored as int32_t. */
typedef enum {
    MRTM_OK                      =  0,  /* ok: Done, nothing wrong. */
    MRTM_ERR_ARG                 =  1,  /* errArg: A caller passed a bad argument (NULL pointer, value out of range). */
    MRTM_ERR_TIMEOUT             =  2,  /* errTimeout: A bus or queue did not answer in time. */
    MRTM_ERR_CRC                 =  3,  /* errCrc: A checksum did not match (probe scratchpad, log record, stored config). */
    MRTM_ERR_RANGE               =  4,  /* errRange: A reading is outside what the part can physically report (-30..50 degC). */
    MRTM_ERR_BUS                 =  5,  /* errBus: A 1-Wire or I2C transaction failed. */
    MRTM_ERR_FLASH               =  6,  /* errFlash: A flash erase or write failed. */
    MRTM_ERR_NVS                 =  7,  /* errNvs: The stored configuration is missing or unreadable. */
    MRTM_ERR_FULL                =  8,  /* errFull: A queue is full; the item was not taken. */
    MRTM_ERR_STATE               =  9,  /* errState: Called in the wrong mode (for example before init). */
    MRTM_ERR_HW                  = 10,  /* errHw: A hardware self-test failed (buzzer current, backup alarm, RTC). */
} mrtm_err_t;

#endif
