// Generate the Phase 6 hardware tables from the SysML model with Sanad's own
// reader: parseSysml for the pins / currents / part numbers (attribute values),
// loadSysmlProject for the satisfy links (the graph facts). Sanad has no
// pin-map, power-budget, BOM or hardware-matrix report (FINDINGS F-57..F-59).
// Exits 1 when a budget or pin rule fails, so it is also the Phase 6 check.
// Usage: node tools/hw-tables.cjs <ext> <repo>
const { join } = require("node:path"); const fs = require("node:fs");
const [ext, root] = process.argv.slice(2);
const d = (m) => require(join(ext, "dist", m));
const { parseSysml } = d("sysml.js"); const { loadSysmlProject } = d("analysis/sysmlProject.js");
const HW = "06-design/hardware/MrtmHardware.sysml", PHYS = "06-design/system/MrtmPhysical.sysml";
const parse = (p) => parseSysml(fs.readFileSync(join(root, p), "utf8"), 0, "model").elements;
const find = (els, kind, name) => els.flatMap((e) => [e, ...e.children]).find((e) => e.kind === kind && e.name === name);
const nameOf = (e) => e.name ?? e.redefines?.[0];
const attrs = (e) => Object.fromEntries((e?.children ?? []).filter((c) => c.kind === "attribute" && c.value !== undefined).map((c) => [nameOf(c), c.value.replace(/^"|"$/g, "")]));
const hwPkg = parse(HW).find((e) => e.kind === "package").children, unit = find(parse(PHYS), "part def", "MrtmUnit"), board = find(hwPkg, "part def", "MrtmBoard");
const ends = Object.fromEntries([...unit.children, ...board.children].filter((c) => c.ends?.length === 2).map((c) => [nameOf(c), c.ends.join(" ↔ ")]));
const defAttrs = (t) => { const e = find(hwPkg, "part def", t) ?? find(hwPkg, "interface def", t); return e ? { ...(e.specializes ?? []).reduce((o, s) => ({ ...o, ...defAttrs(s) }), {}), ...attrs(e) } : {}; };
const fail = []; const out = (f, lines) => fs.writeFileSync(join(root, "09-hardware", f), lines.join("\n") + "\n");
const head = (t, std) => [`# ${t}`, "", `> GENERATED by \`tools/hw-tables.cjs\` from \`${HW}\` with Sanad's own SysML reader — edit the model, not this file. ${std}`, "> Every value is EE-REVIEW (an electrical engineer confirms it against the real datasheets). Vendors and part numbers are SYNTHETIC.", ""];

// Pin map: every GPIO attribute on a board connection, plus the module's fixed USB pins.
const RESERVED = new Set([0, 3, 45, 46, 19, 20, ...Array.from({ length: 12 }, (_, i) => 26 + i)]);
const pins = [];
for (const c of board.children.filter((c) => c.kind === "interface")) {
  const a = { ...defAttrs(c.types[0]), ...attrs(c) };
  for (const [k, v] of Object.entries(a)) if (/gpio$/i.test(k)) pins.push({ gpio: Number(v), signal: `${nameOf(c)}.${k}`, type: c.types[0], ends: ends[nameOf(c)] ?? "", extra: Object.entries(a).filter(([x]) => !/gpio$/i.test(x)).map(([x, y]) => `${x}=${y}`).join(", ") });
}
const mod = defAttrs("Esp32S3Module");
pins.push({ gpio: Number(mod.usbDMinusGpio), signal: "usb.D-", type: "native USB", ends: "esp32.usb ↔ host", extra: "fixed function", fixed: true }, { gpio: Number(mod.usbDPlusGpio), signal: "usb.D+", type: "native USB", ends: "esp32.usb ↔ host", extra: "fixed function", fixed: true });
pins.sort((a, b) => a.gpio - b.gpio);
const byPin = {}; for (const p of pins) (byPin[p.gpio] ??= new Set()).add(p.signal.replace(/^(displayLink|clockLink)\./, "i2c."));
for (const [g, s] of Object.entries(byPin)) if (s.size > 1) fail.push(`GPIO${g} carries ${[...s].join(" and ")}`);
for (const p of pins) if (!p.fixed && RESERVED.has(p.gpio)) fail.push(`GPIO${p.gpio} (${p.signal}) is a strapping, flash or USB pin`);
out("pin-map.md", [...head("Pin map — ESP32-S3 GPIO allocation", "IEC 62304 cl. 5.3.3; IEC 60601-1 frame."),
  "| GPIO | Signal (connection.attribute) | Interface | Connects | Other settings |", "|---|---|---|---|---|",
  ...pins.map((p) => `| ${p.gpio} | ${p.signal} | ${p.type} | ${p.ends} | ${p.extra} |`), "",
  `Rules checked: no pin carries two signals (the I²C pair is one shared bus); no signal on a strapping (0, 3, 45, 46), flash/PSRAM (26–37) or USB (19, 20) pin. Result: ${fail.length ? "FAIL" : "pass"}.`]);

// Power budget and BOM: every board part, its chosen type, its currents.
const parts = board.children.filter((c) => c.kind === "part").map((c) => ({ ref: nameOf(c), type: c.types[0], ...defAttrs(c.types[0]), ...attrs(c) }));
const sum = (k) => parts.reduce((s, p) => s + Number(p[k] ?? 0), 0);
const [normal, alarm] = [sum("normalMa"), sum("alarmMa")];
const cell = parts.find((p) => p.ref === "battery"), cap = parts.find((p) => p.ref === "holdUpCap");
const usable = Number(cell.capacityMah) * Number(cell.usableFraction), hNormal = usable / normal, hAlarm = usable / alarm;
const backupMa = Number(parts.find((p) => p.ref === "buzzer").alarmMa) + Number(parts.find((p) => p.ref === "backupAlarm").alarmMa);
const holdS = (Number(cap.capacitanceF) * Number(cap.lifeDerating) * (Number(cap.voltsFull) - Number(cap.voltsMin))) / (backupMa / 1000);
if (Math.min(hNormal, hAlarm) < 4) fail.push(`battery lasts ${Math.min(hNormal, hAlarm).toFixed(1)} h < 4 h (MRTM-ENV-001)`);
if (holdS < 60) fail.push(`hold-up alarm lasts ${holdS.toFixed(0)} s < 60 s (MRTM-SAF-013)`);
const f = (x) => Number(x).toFixed(2);
out("power-budget.md", [...head("Power budget", "IEC 60601-1 cl. 4.7 (single fault: mains lost), cl. 11; MRTM-ENV-001, MRTM-SAF-013."),
  "| Part | Component | Normal mA (EE-REVIEW) | Alarm mA (EE-REVIEW) |", "|---|---|---|---|",
  ...parts.map((p) => `| ${p.ref} | ${p.type} | ${f(p.normalMa ?? 0)} | ${f(p.alarmMa ?? 0)} |`),
  `| **Total** | | **${f(normal)}** | **${f(alarm)}** |`, "",
  `- Battery: ${cell.capacityMah} mAh × ${cell.usableFraction} usable = ${usable.toFixed(0)} mAh → **${hNormal.toFixed(1)} h** normal, **${hAlarm.toFixed(1)} h** alarm; required 4 h (MRTM-ENV-001, A-11). EE-REVIEW.`,
  `- Hold-up: ${cap.capacitanceF} F × ${cap.lifeDerating} life derating × (${cap.voltsFull} − ${cap.voltsMin}) V ÷ ${f(backupMa)} mA (buzzer + timer) = **${holdS.toFixed(0)} s**; required 60 s (MRTM-SAF-013). EE-REVIEW.`,
  `- Result: ${fail.some((x) => /lasts/.test(x)) ? "FAIL" : "pass"}.`]);
out("bom.md", [...head("Bill of materials — modelled components", "IEC 60601-1 cl. 4.8 (components). No prices (synthetic run)."),
  "| Ref | Qty | Component (model type) | Part number | Vendor |", "|---|---|---|---|---|",
  ...parts.map((p) => `| ${p.ref} | 1 | ${p.type} | ${p.partNumber ?? "—"} | ${p.vendor ?? "—"} |`), "",
  "Passives (pull-ups, dividers, MOSFET, diodes, comparator, connectors, PCB, enclosure) are not modelled: see hardware-design-description.md §6 (MANUAL, F-58)."]);

// Hardware traceability matrix: satisfy links whose target is a hardware element.
(async () => {
  const hwNames = new Set([...unit.children, ...board.children].map(nameOf).filter(Boolean));
  const p = await loadSysmlProject(root, ["06-design"]);
  const links = p.facts.relations.filter((r) => /^MRTM-/.test(r.from)).map((r) => ({ req: r.from, el: String(r.to).replace(/^hardware\./, ""), src: r.source }))
    .filter((r) => hwNames.has(r.el) && !/MrtmPartitions/.test(r.src));
  const reqs = [...new Set(links.map((l) => l.req))].sort(), cols = [...new Set(links.map((l) => l.el))].sort();
  const all = p.facts.relations.filter((r) => /^MRTM-/.test(r.from)).map((r) => r.from);
  const swOnly = [...new Set(all)].filter((r) => !reqs.includes(r)).sort();
  out("hardware-trace-matrix.md", [...head("Hardware traceability matrix — requirement × hardware element", "IEC 62304 cl. 5.3.3, 7.3.3; ISO 14971 cl. 7.2. Marks are SysML `satisfy` links read by Sanad's `loadSysmlProject` from MrtmPhysical, MrtmHardware and MrtmSafety."),
    `**${reqs.length} requirements × ${cols.length} hardware elements, ${new Set(links.map((l) => l.req + l.el)).size} marks.** Requirements with no mark on a single hardware element (met by software, or by the whole unit "hardware" in MrtmPartitions): ${swOnly.length} — ${swOnly.join(", ")}.`, "",
    `| Requirement | ${cols.join(" | ")} |`, `|---|${cols.map(() => ":-:").join("|")}|`,
    ...reqs.map((r) => `| ${r} | ${cols.map((c) => (links.some((l) => l.req === r && l.el === c) ? "●" : "")).join(" | ")} |`)]);
  console.log(`pins ${pins.length}, parts ${parts.length}, normal ${f(normal)} mA, alarm ${f(alarm)} mA, battery ${hNormal.toFixed(1)}/${hAlarm.toFixed(1)} h, hold-up ${holdS.toFixed(0)} s, matrix ${reqs.length}x${cols.length}`);
  for (const x of fail) console.log(`FAIL: ${x}`);
  process.exit(fail.length ? 1 : 0);
})().catch((e) => { console.error(e.stack); process.exit(2); });
