#!/usr/bin/env python3
"""Unit / integration / system verification records (IEC 62304 §5.5.5, §5.6.7, §5.7.5) from the JUnit
result rows Sanad reads — so the record and Sanad's view cannot disagree. Usage (repo root): verification-records.py"""
import glob, pathlib, xml.etree.ElementTree as ET
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "11-verification/records"; OUT.mkdir(exist_ok=True)
CLAUSE = {"unit": "IEC 62304 §5.5.5 (software unit verification record)", "integration": "IEC 62304 §5.6.7 (integration test record)",
          "system": "IEC 62304 §5.7.5 (software system test record)"}
DEFECTS = {"unit": "DEF-001 (ring size), DEF-005 (stale objects) — closed before this run", "integration": "DEF-002 (restore vs self-test), DEF-003 (clock never refreshed) — closed before this run",
           "system": "DEF-004 (host scheduler) — closed before this run; DEF-006 (no backup-alarm sense line) — open, blocks SP-05 on the bench"}
for level in ("unit", "integration", "system"):
    rows, props, n = [], {}, [0, 0, 0]
    for x in sorted(glob.glob(str(ROOT / f"11-verification/results/{level}/*.xml"))):
        s = ET.parse(x).getroot()
        props = {p.get("name"): p.get("value") for p in s.iter("property")}
        cases = list(s.iter("testcase"))
        f = sum(1 for c in cases if c.find("failure") is not None); b = sum(1 for c in cases if c.find("skipped") is not None)
        n = [n[0] + len(cases) - f - b, n[1] + f, n[2] + b]
        if level == "system":
            for c in cases:
                sk = c.find("skipped"); rows.append(f"| {c.get('name')} | {'blocked — ' + sk.get('message') if sk is not None else ('FAIL' if c.find('failure') is not None else 'pass')} |")
        else:
            rows.append(f"| {s.get('name')} | {len(cases)} | {len(cases) - f - b} | {f} | {b} | {pathlib.Path(x).relative_to(ROOT)} |")
    head = "| Case | Verdict |\n|---|---|" if level == "system" else "| Runner | Tests | Pass | Fail | Blocked | Result file (Sanad reads it) |\n|---|---|---|---|---|---|"
    (OUT / f"{level}-verification-record.md").write_text(f"""# {level.capitalize()} verification record — MRTM

> **Standard:** {CLAUSE[level]}, Class C. **Status:** DRAFT — needs Masood's review. Generated by `tools/verification-records.py` from the result rows in 11-verification/results/{level}/.

| Field | Value |
|---|---|
| Build (git sha of the code) | {props.get('build')} |
| Date | {props.get('date')} |
| Tester | {props.get('tester')} — **independence: none** (owner order 3: not required) |
| Environment | {props.get('environment')} (see ../strategy/verification-strategy.md §4) |
| Evidence | 11-verification/evidence/ ({props.get('evidence')}) |
| Totals | pass {n[0]} · fail {n[1]} · blocked {n[2]} |
| Anomalies found on the way | {DEFECTS[level]} |

{head}
{chr(10).join(rows)}

**Conclusion (plain words):** {"every automated test passed on the host build." if level != "system" else "the host dry run of the excursion cycle passed all 10 checks; every bench and inspection procedure is blocked because no board or instruments exist in this run — those requirements are NOT verified yet."}
""")
    print(level, n)
