#!/usr/bin/env python3
"""RUN-04: writes the SysML v2 model of the aerospace ladder into 06-design/<node-path>/.
Structure is written below as text (MANUAL, run 2 F-127); `satisfy` lines are generated from the requirement
folders: a node satisfies ITS OWN requirements only (rule satisfy: own-node-only).
Usage (run folder): python3 tools/aero_model.py.  DRAFT — needs Masood's review."""
import json, pathlib, re, sys, yaml
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from aero_data import REQS
FW = yaml.safe_load((ROOT / ".ejadah/rew/framework.yaml").read_text())
IDS = json.loads((ROOT / "tools/aero-ids.json").read_text())
D = ROOT / "06-design"

def reqs_in(folder):
    return sorted(p.stem for p in (ROOT / "03-requirements" / folder).rglob("MRTM-*.md"))

def write(rel, head, pkg, doc, body, sat=None):
    lines = [f"// {pkg} — RUN-04 aerospace ladder. Generated by tools/aero_model.py — edit there.", *head, "", f"package {pkg} {{", "",
             f"    doc /* {doc} */", body.rstrip()]
    if sat:
        lines.append("")
        lines += [f"    satisfy '{r}' by {by};" for r, by in sat]
    lines.append("}")
    p = D / rel; p.parent.mkdir(parents=True, exist_ok=True); p.write_text("\n".join(lines) + "\n")
    return len(sat or [])

def imp(*names): return [f"private import {n}::*;" for n in names]

PORTS = """
    // Flows between items (what crosses an item boundary).
    port def SampleFlow { out item sample : TemperatureSample; }
    port def AlarmStateFlow { out item alarmState : ExcursionState; }
    port def RecordFlow { out item rec : LogRecord; }
    port def PowerEventFlow { out item evt : PowerEvent; }
    port def HeartbeatFlow { out attribute beat : Natural; }
    port def BandFlow { out attribute bandLowTenths : Integer; out attribute bandHighTenths : Integer; }
    port def HistoryFlow { out item file : LogFile; }
    // What people meet: the alarm signals (sound, light, button) and the screen.
    port def AlarmHmiPort { out item signal : AlarmCommand; in item press : ButtonPress; }
    port def ScreenPort { out item screenFrame : DisplayFrame; }
    item def LowPriorityLight :> AlarmCommand;
    item def ExcursionSound :> AlarmCommand;
    item def AudioPaused :> AlarmCommand;
    part def Staff {
        doc /* The people at the monitor: nurse, pharmacist, manager, technician. */
        port alarmSignals : ~AlarmHmiPort;
        port screen : ~ScreenPort;
    }
    // DO-178C §2.3 software level / ARP4754A item development assurance level.
    enum def DesignAssuranceLevel {
        enum A;  // catastrophic failure condition
        enum B;  // hazardous
        enum C;  // major
        enum D;  // minor
        enum E;  // no safety effect
    }
"""

def dal(node): return f"attribute itemDal : DesignAssuranceLevel = DesignAssuranceLevel::{next(n['dal'] for n in FW['nodes'] if n['name'] == node)};"

# ---- items: (node, part def, usage, ports, doc) --------------------------------------------------
HW = [
 ("sensor-hw", "SensorHw", "sensorHw", ["port air : ~ThermalPort;", "port bus : ~OneWirePort;"],
  "The temperature probe on its 1-Wire bus (DS18B20 class, synthetic)."),
 ("alarm-hw", "AlarmHw", "alarmHw", ["port buzzerDrive : ~GpioOutPort;", "port redLed : ~GpioOutPort;", "port wdtPulse : ~GpioOutPort;",
   "port ack : ~GpioInPort;", "port buzzerSense : ~GpioInPort;", "port supply : ~PowerPort;", "port alarmSignals : AlarmHmiPort;"],
  "Buzzer, red and green lights, acknowledge button and the backup alarm (external watchdog timer, driver, hold-up store)."),
 ("controller-hw", "ControllerHw", "controllerHw", ["port probeBus : OneWirePort;", "port i2c : I2cPort;", "port buzzerDrive : GpioOutPort;",
   "port redLed : GpioOutPort;", "port wdtPulse : GpioOutPort;", "port ack : GpioInPort;", "port buzzerSense : GpioInPort;", "port mainsSense : GpioInPort;",
   "port usb : UsbPort;", "port supply : ~PowerPort;"],
  "The processor board: ESP32-S3 class microcontroller, real-time clock, flash. Hosts all five software items."),
 ("power-hw", "PowerHw", "powerHw", ["port mains : ~PowerPort;", "port supply : PowerPort;", "port mainsSense : ~GpioInPort;"],
  "Mains adapter input, power path and the Li-ion battery."),
 ("display-hw", "DisplayHw", "displayHw", ["port i2c : ~I2cPort;", "port supply : ~PowerPort;", "port screen : ScreenPort;"],
  "The 0.96 in OLED panel on the I2C bus."),
]
SW = [
 ("alarm-sw", "AlarmSw", "alarmSw", ["port samples : SampleFlow;", "port alarmState : AlarmStateFlow;", "port records : RecordFlow;",
   "port heartbeat : HeartbeatFlow;", "port band : ~BandFlow;", "port powerEvents : ~PowerEventFlow;"],
  "Samples the probe, decides early / confirmed / ended excursions and drives the alarm signals. The alarm path."),
 ("platform-sw", "PlatformSw", "platformSw", ["port heartbeat : ~HeartbeatFlow;", "port band : BandFlow;", "port powerEvents : PowerEventFlow;", "port records : RecordFlow;"],
  "Power-up order and self-tests, the band check, the watchdog gate, mains and battery events, task priorities."),
 ("display-sw", "DisplaySw", "displaySw", ["port samples : ~SampleFlow;", "port alarmState : ~AlarmStateFlow;"],
  "Draws the temperature, the warning and the maintenance messages."),
 ("record-sw", "RecordSw", "recordSw", ["port records : ~RecordFlow;", "port history : HistoryFlow;"],
  "Time-stamps every event and keeps two copies in flash."),
 ("export-sw", "ExportSw", "exportSw", ["port history : ~HistoryFlow;"],
  "Shows the history to a USB host as a read-only volume."),
]
DESIGN = {  # software design: components of the library (MrtmSoftware) and their tasks
 "alarm-sw": ("AlarmSwDesign", ["sensorSampler : SensorSampler", "limitEvaluator : LimitEvaluator", "alarmMgr : AlarmMgr", "sensorTask : SensorTask", "alarmTask : AlarmTask"],
   ["connect sensorSampler.samples to limitEvaluator.samples;", "connect limitEvaluator.excursion to alarmMgr.excursion;",
    "allocate sensorSampler to sensorTask;", "allocate limitEvaluator to sensorTask;", "allocate alarmMgr to alarmTask;"]),
 "platform-sw": ("PlatformSwDesign", ["wdtKicker : WdtKicker", "diagnostics : Diagnostics", "configMgr : ConfigMgr", "powerMon : PowerMon", "supervisorTask : SupervisorTask"],
   ["allocate wdtKicker to supervisorTask;", "allocate diagnostics to supervisorTask;", "allocate configMgr to supervisorTask;", "allocate powerMon to supervisorTask;"]),
 "display-sw": ("DisplaySwDesign", ["displayMgr : DisplayMgr", "displayTask : DisplayTask"], ["allocate displayMgr to displayTask;"]),
 "record-sw": ("RecordSwDesign", ["eventLog : EventLog", "historyRing : HistoryRingStore", "rtcClock : RtcClock", "logTask : LogTask"],
   ["allocate eventLog to logTask;", "allocate historyRing to logTask;", "allocate rtcClock to logTask;"]),
 "export-sw": ("ExportSwDesign", ["usbExport : UsbExport", "usbTask : UsbTask"], ["allocate usbExport to usbTask;"]),
}
COMP = {"sensor_sampler": "sensorSampler", "limit_evaluator": "limitEvaluator", "alarm_mgr": "alarmMgr", "wdt_kicker": "wdtKicker",
        "diagnostics": "diagnostics", "config_mgr": "configMgr", "power_mon": "powerMon", "display_mgr": "displayMgr",
        "event_log": "eventLog", "history_ring": "historyRing", "rtc_clock": "rtcClock", "usb_export": "usbExport"}

def pkg(name): return "Node" + "".join(w.capitalize() for w in name.split("-"))

def main():
    n = 0
    (D / "common/AeroPorts.sysml").write_text("// AeroPorts — RUN-04 vocabulary shared by the ladder (flows, people, DAL). No satisfy here.\n"
        + "\n".join(imp("ScalarValues", "MrtmInterfaces")) + "\n\npackage AeroPorts {\n" + PORTS + "}\n")
    # ---- aircraft ----
    n += write("aircraft/NodeAircraft.sysml", imp("ScalarValues", "ProjectRequirements", "MrtmInterfaces", "AeroPorts"), "NodeAircraft",
      "AIRCRAFT LEVEL (ARP4754A §5.1): the monitor as ONE product among its neighbours, and its five functions. Satisfies the stakeholder needs, the product functions and the FHA safety objectives only.",
      """
    part def MonitorDevice {
        doc /* The product seen from outside: what the clinic touches. DAL A (FHA, 08-safety/01-fha.md). */
        port air : ~ThermalPort;
        port mains : ~PowerPort;
        port usb : UsbPort;
        port alarmSignals : AlarmHmiPort;
        port screen : ScreenPort;
    }
    part monitor : MonitorDevice;
""", [(r, "monitor") for r in reqs_in("aircraft")])
    write("aircraft/AircraftContext.sysml", imp("MrtmInterfaces", "MrtmSystemContext", "AeroPorts", "NodeAircraft"), "AircraftContext",
      "The monitor among the things it touches (package-level parts so the canvas can place them, F-129). No satisfy here.", """
    part fridge : Fridge;
    part monitor : MonitorDevice;
    part mains : MainsSupply;
    part usbHost : UsbHost;
    part staff : Staff;
    interface airContact : ThermalContact connect fridge.air to monitor.air;
    interface mainsFeed : PowerFeed connect mains.output to monitor.mains;
    interface historyLink : UsbLink connect monitor.usb to usbHost.usb;
    connect monitor.alarmSignals to staff.alarmSignals;
    connect monitor.screen to staff.screen;
""")
    write("aircraft/AircraftFunctions.sysml", imp("MrtmInterfaces"), "AircraftFunctions",
      "The five product functions (ARP4754A aircraft-level functions): MRTM-FUN-001…005. The FHA asks of each how it can fail.", """
    action def ProductFunctions {
        action monitorAir { doc /* MRTM-FUN-001 */ out item sample : TemperatureSample; }
        action warnExcursion { doc /* MRTM-FUN-002 */ in item sample : TemperatureSample; out item excursion : ExcursionState; }
        action acknowledgeWarning { doc /* MRTM-FUN-003 */ in item excursion : ExcursionState; }
        action keepHistory { doc /* MRTM-FUN-004 */ in item excursion : ExcursionState; }
        action watchThroughPowerCut { doc /* MRTM-FUN-005 */ out item power : PowerEvent; }
        flow of TemperatureSample from monitorAir.sample to warnExcursion.sample;
        flow of ExcursionState from warnExcursion.excursion to acknowledgeWarning.excursion;
        flow of ExcursionState from warnExcursion.excursion to keepHistory.excursion;
        succession first monitorAir then warnExcursion;
    }
""")
    # ---- items ----
    for node, pd, use, ports, doc in HW + SW:
        body = f"\n    part def {pd} {{\n        doc /* {doc} */\n        {dal(node)}\n" + "".join(f"        {p}\n" for p in ports) + f"    }}\n    part {use} : {pd};\n"
        kind = "hwr" if node.endswith("-hw") else "hlr"
        n += write(f"{FW_PATH(node)}/{pkg(node)}.sysml", imp("ScalarValues", "ProjectRequirements", "MrtmInterfaces", "AeroPorts"), pkg(node),
                   f"ITEM `{node}` (ARP4754A §5.3 item, DAL {next(x['dal'] for x in FW['nodes'] if x['name'] == node)}). Satisfies its own {'hardware item requirements' if kind == 'hwr' else 'high-level requirements (DO-178C §5.1)'} only.",
                   body, [(r, use) for r in reqs_in(f"{kind}/{node}")])
    # ---- software designs (DO-178C §5.2: architecture + LLR) ----
    site_comp = {}
    for key, typ, node, *_, x in REQS:
        for f, ln in x.get("sites", []): site_comp[IDS[key]] = COMP.get(f.split("/")[2])
    for item, (pd, parts, links) in DESIGN.items():
        use = pd[0].lower() + pd[1:]
        arch = pd.replace("Design", "Architecture")
        write(f"{FW_PATH(item)}/design/{arch}.sysml", imp("ScalarValues", "SoftwareProfile", "MrtmInterfaces", "MrtmSoftware"), arch,
              f"Software architecture of `{item}` (DO-178C §5.2.1) with Sanad's software profile (#Component, #Thread from MrtmSoftware). No satisfy here.",
              f"\n    part def {pd} {{\n" + "".join(f"        part {p};\n" for p in parts) + "".join(f"        {l}\n" for l in links) + "    }\n")
        body = f"\n    part {use} : {pd};\n"
        sat = [(r, f"{use}.{site_comp[r]}" if site_comp.get(r) else use) for r in reqs_in(f"llr/{item}")]
        n += write(f"{FW_PATH(item)}/design/{pkg(item + '-design')}.sysml",
                   imp("ScalarValues", "ProjectRequirements", arch), pkg(item + "-design"),
                   f"SOFTWARE DESIGN of `{item}` (DO-178C §5.2): its architecture and its low-level requirements. Satisfies its own LLR only, each by the component whose code implements it.",
                   body, sat)
    # ---- system ----
    items = HW + SW
    n += write("system/NodeSystem.sysml", imp("ScalarValues", "ProjectRequirements", "MrtmInterfaces", "AeroPorts", "NodeAircraft", *[pkg(i[0]) for i in items]), "NodeSystem",
      "SYSTEM LEVEL (ARP4754A §5.2–5.3): the monitoring system and its ten items. Satisfies the system requirements only.",
      "\n    part def MonitorSystem :> MonitorDevice {\n        doc /* The system: five hardware items, five software items hosted on the controller hardware. */\n"
      + "".join(f"        part {u} : {p};\n" for _, p, u, *_ in items)
      + "".join(f"        allocate {u} to controllerHw;\n" for _, p, u, *_ in SW) + "    }\n    part system : MonitorSystem;\n",
      [(r, "system") for r in reqs_in("system")])
    write("system/SystemItems.sysml", imp("AeroPorts", *[pkg(i[0]) for i in items]), "SystemItems",
      "The ten items of the system and their DAL, as one tree (item block view). No satisfy here.",
      "\n    part def MonitorSystemItems {\n" + "".join(f"        part {u} : {p};\n" for _, p, u, *_ in items) + "    }\n")
    write("system/SystemHardware.sysml", imp("MrtmInterfaces", "MrtmSystemContext", "AeroPorts", *[pkg(i[0]) for i in HW]), "SystemHardware",
      "Hardware item interconnection: the five hardware items, their buses and lines, and the neighbours the boundary meets (package-level parts, F-129). No satisfy here.", """
    part sensorHw : SensorHw;
    part controllerHw : ControllerHw;
    part alarmHw : AlarmHw;
    part displayHw : DisplayHw;
    part powerHw : PowerHw;
    part fridge : Fridge;
    part mains : MainsSupply;
    part staff : Staff;
    interface airContact : ThermalContact connect fridge.air to sensorHw.air;
    interface probeBus : ProbeBus connect controllerHw.probeBus to sensorHw.bus;
    interface displayBus : I2cBus connect controllerHw.i2c to displayHw.i2c;
    interface buzzerLine : SignalLine connect controllerHw.buzzerDrive to alarmHw.buzzerDrive;
    interface ledLine : SignalLine connect controllerHw.redLed to alarmHw.redLed;
    interface watchdogLine : SignalLine connect controllerHw.wdtPulse to alarmHw.wdtPulse;
    interface ackLine : ButtonLine connect controllerHw.ack to alarmHw.ack;
    interface currentSense : SenseLine connect controllerHw.buzzerSense to alarmHw.buzzerSense;
    interface mainsSense : SenseLine connect controllerHw.mainsSense to powerHw.mainsSense;
    interface mainsFeed : PowerFeed connect mains.output to powerHw.mains;
    interface boardFeed : PowerFeed connect powerHw.supply to controllerHw.supply;
    interface alarmFeed : PowerFeed connect powerHw.supply to alarmHw.supply;
    interface displayFeed : PowerFeed connect powerHw.supply to displayHw.supply;
    connect alarmHw.alarmSignals to staff.alarmSignals;
    connect displayHw.screen to staff.screen;
""")
    write("system/SystemSoftware.sysml", imp("AeroPorts", *[pkg(i[0]) for i in SW]), "SystemSoftware",
      "Software item interconnection: the five software items and the flows between them (all hosted on the controller hardware). No satisfy here.", """
    part alarmSw : AlarmSw;
    part platformSw : PlatformSw;
    part displaySw : DisplaySw;
    part recordSw : RecordSw;
    part exportSw : ExportSw;
    connect alarmSw.samples to displaySw.samples;
    connect alarmSw.alarmState to displaySw.alarmState;
    connect alarmSw.records to recordSw.records;
    connect platformSw.records to recordSw.records;
    connect alarmSw.heartbeat to platformSw.heartbeat;
    connect platformSw.band to alarmSw.band;
    connect platformSw.powerEvents to alarmSw.powerEvents;
    connect recordSw.history to exportSw.history;
""")
    write("system/AlarmPathSequence.sysml", imp("MrtmInterfaces", "MrtmSystemContext", "AeroPorts", "NodeSensorHw", "NodeAlarmSw", "NodeAlarmHw", "NodeRecordSw"), "AlarmPathSequence",
      "The alarm path at ITEM granularity: warm air → sensor hardware → alarm software (early light, then 31 samples / 60 s, then buzzer) → alarm hardware → staff; the record software logs it. Budgets: sample 2 s + conversion 0.75 s + one 1 s alarm cycle ≤ 5 s (ADR-0030). Timing is text only (run 2 F-123).", """
    part fridge : Fridge;
    part sensorHw : SensorHw;
    part alarmSw : AlarmSw;
    part alarmHw : AlarmHw;
    part recordSw : RecordSw;
    part staff : Staff;
    message warmAir of AirHeat from fridge to sensorHw;
    message sample of TemperatureSample from sensorHw to alarmSw;
    message earlyDrive of LowPriorityLight from alarmSw to alarmHw;
    message earlyLight of LowPriorityLight from alarmHw to staff;
    message buzzerDrive of ExcursionSound from alarmSw to alarmHw;
    message sounding of ExcursionSound from alarmHw to staff;
    message logStart of LogRecord from alarmSw to recordSw;
    message acknowledge of ButtonPress from staff to alarmHw;
    message ackLine of ButtonPress from alarmHw to alarmSw;
    message silence of AudioPaused from alarmSw to alarmHw;
    succession first warmAir then sample;
    succession first sample then earlyDrive;
    succession first earlyDrive then earlyLight;
    succession first earlyLight then buzzerDrive;
    succession first buzzerDrive then sounding;
    succession first sounding then logStart;
    succession first logStart then acknowledge;
    succession first acknowledge then ackLine;
    succession first ackLine then silence;
""")
    write("system/SystemFunctions.sysml", imp("MrtmInterfaces"), "SystemFunctions",
      "Functional decomposition at SYSTEM level: the nine system functions the items perform (from run 2's MrtmLogical, without the performers). No satisfy here.", """
    action def MonitoringFunctions {
        action acquireSample { doc /* sensor-hw, alarm-sw */ out item sample : TemperatureSample; }
        action checkProbe { doc /* alarm-sw */ in item sample : TemperatureSample; out item valid : TemperatureSample; }
        action detectExcursion { doc /* alarm-sw */ in item valid : TemperatureSample; out item excursion : ExcursionState; }
        action annunciateAlarm { doc /* alarm-sw, alarm-hw */ in item excursion : ExcursionState; out item command : AlarmCommand; }
        action showStatus { doc /* display-sw, display-hw */ in item excursion : ExcursionState; }
        action recordEvent { doc /* record-sw */ in item excursion : ExcursionState; in item power : PowerEvent; out item record : LogRecord; }
        action serveHistory { doc /* export-sw */ in item record : LogRecord; }
        action supervisePower { doc /* power-hw, platform-sw */ out item power : PowerEvent; }
        action superviseSoftware { doc /* platform-sw, controller-hw, backup alarm */ }
        flow of TemperatureSample from acquireSample.sample to checkProbe.sample;
        flow of TemperatureSample from checkProbe.valid to detectExcursion.valid;
        flow of ExcursionState from detectExcursion.excursion to annunciateAlarm.excursion;
        flow of ExcursionState from detectExcursion.excursion to showStatus.excursion;
        flow of ExcursionState from detectExcursion.excursion to recordEvent.excursion;
        flow of PowerEvent from supervisePower.power to recordEvent.power;
        flow of LogRecord from recordEvent.record to serveHistory.record;
    }
""")
    write("items/alarm-sw/AlarmSwFunctions.sysml", imp("MrtmInterfaces", "MrtmSwStates"), "AlarmSwFunctions",
      "Functional decomposition of the alarm software item (item level): what its HLR ask, in order. No satisfy here.", """
    action def AlarmPath {
        action sampleProbe { doc /* HLR-001 */ out item raw : TemperatureSample; }
        action checkSample { doc /* HLR-002, HLR-003 */ in item raw : TemperatureSample; out item valid : TemperatureSample; }
        action countExcursion { doc /* HLR-004…006 */ in item valid : TemperatureSample; out item excursion : ExcursionState; }
        action decideAlarm { doc /* HLR-007…015: the alarm state machine */ in item excursion : ExcursionState; in item press : ButtonPress; out item command : AlarmCommand; }
        action driveSignals { doc /* buzzer, red light */ in item command : AlarmCommand; }
        action beatHeart { doc /* HLR-010 */ }
        flow of TemperatureSample from sampleProbe.raw to checkSample.raw;
        flow of TemperatureSample from checkSample.valid to countExcursion.valid;
        flow of ExcursionState from countExcursion.excursion to decideAlarm.excursion;
        flow of AlarmCommand from decideAlarm.command to driveSignals.command;
        succession first decideAlarm then beatHeart;
    }
""")
    print(f"model: {n} satisfy lines")

def FW_PATH(node): return next(x["path"] for x in FW["nodes"] if x["name"] == node)

if __name__ == "__main__":
    main()
