#!/usr/bin/env python3
"""Generate mrtm_errors.h and mrtm_events.h from the SysML enum defs (ADR-0025).
The model (06-design/library/MrtmSwCodes.sysml) stays the source: each line
`enum name; // C_NAME = value: meaning` becomes one C constant. Run with --check to
fail when the headers on disk differ from what the model says (Phase 9 build step)."""
import re, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
MODEL = ROOT / "06-design/library/MrtmSwCodes.sysml"
OUT = ROOT / "10-src/firmware/components/mrtm_common/include"
LINE = re.compile(r"^\s*enum (\w+);\s*//\s*(MRTM_\w+) = (\d+): (.*)$")

def enums():
    cur, out = None, {}
    for ln in MODEL.read_text().splitlines():
        m = re.match(r"^\s*enum def (\w+)", ln)
        if m: cur = m.group(1); out[cur] = []; continue
        m = LINE.match(ln)
        if m and cur: out[cur].append(m.groups())
    return out

def header(guard, ctype, base, rows, what):
    body = "\n".join(f"    {c:<28} = {v:>2},  /* {s}: {t} */" for s, c, v, t in rows)
    return (f"/* {guard.lower()}.h — GENERATED by tools/gen-codes.py from {MODEL.relative_to(ROOT)}\n"
            f" * ({what}). Do not edit: change the model and re-run. IEC 62304 §5.4.2, Class C. */\n"
            f"#ifndef {guard}_H\n#define {guard}_H\n#include <stdint.h>\n\n"
            f"/* Stored as {ctype}. */\ntypedef enum {{\n{body}\n}} {base};\n\n#endif\n")

def main():
    e = enums()
    assert len(e["ErrorCode"]) == 11 and len(e["EventKind"]) == 20, {k: len(v) for k, v in e.items()}
    files = {"mrtm_errors.h": header("MRTM_ERRORS", "int32_t", "mrtm_err_t", e["ErrorCode"], "MrtmSwCodes::ErrorCode"),
             "mrtm_events.h": header("MRTM_EVENTS", "uint8_t", "mrtm_event_kind_t", e["EventKind"], "MrtmSwCodes::EventKind")}
    bad = [n for n, t in files.items() if "--check" in sys.argv and (OUT / n).read_text() != t]
    if "--check" in sys.argv:
        print("codes: headers match the model" if not bad else f"codes: STALE {bad}"); return 1 if bad else 0
    for n, t in files.items(): (OUT / n).write_text(t)
    print(f"codes: wrote {', '.join(files)} ({len(e['ErrorCode'])} errors, {len(e['EventKind'])} events)")
    return 0

sys.exit(main())
