/* mrtm_events.h — GENERATED by tools/gen-codes.py from 06-design/library/software/MrtmSwCodes.sysml
 * (MrtmSwCodes::EventKind). Do not edit: change the model and re-run. IEC 62304 §5.4.2, Class C. */
#ifndef MRTM_EVENTS_H
#define MRTM_EVENTS_H
#include <stdint.h>

/* Stored as uint8_t. */
typedef enum {
    MRTM_EV_EXCURSION_START      =  1,  /* excursionStart: An excursion was confirmed. (MRTM-SYS-008) */
    MRTM_EV_EXCURSION_END        =  2,  /* excursionEnd: An excursion ended; the record carries the peak. (MRTM-SYS-009) */
    MRTM_EV_ACK                  =  3,  /* acknowledged: Staff pressed the acknowledge button during an alarm. (MRTM-SYS-010) */
    MRTM_EV_POWER_LOSS           =  4,  /* powerLoss: Mains power was lost. (MRTM-SAF-005) */
    MRTM_EV_POWER_RESTORE        =  5,  /* powerRestore: Mains power came back. (MRTM-SYS-023) */
    MRTM_EV_PROBE_FAULT          =  6,  /* probeFault: The probe fault was declared. (MRTM-SYS-012) */
    MRTM_EV_PROBE_RECOVERED      =  7,  /* probeRecovered: Good samples arrived again after a probe fault. (MRTM-SYS-012) */
    MRTM_EV_BUZZER_FAULT         =  8,  /* buzzerFault: The buzzer drew too little current while driven. (MRTM-SAF-014) */
    MRTM_EV_BUTTON_FAULT         =  9,  /* buttonFault: The acknowledge button stayed pressed for 60 s. (MRTM-SAF-019) */
    MRTM_EV_CLOCK_FAULT          = 10,  /* clockFault: The RTC reported an oscillator stop at power-up. (MRTM-SAF-022) */
    MRTM_EV_CONFIG_CRC_FAULT     = 11,  /* configCrcFault: The stored allowed band failed its CRC-32 check. (MRTM-SAF-017) */
    MRTM_EV_SELF_TEST_PASS       = 12,  /* selfTestPass: All power-up tests passed. (MRTM-SAF-007) */
    MRTM_EV_SELF_TEST_FAIL       = 13,  /* selfTestFail: A power-up test failed; the record's value says which. (MRTM-SAF-023) */
    MRTM_EV_LOW_BATTERY          = 14,  /* lowBattery: The battery fell below 3.4 V. (MRTM-SAF-008) */
    MRTM_EV_WATCHDOG_RESTART     = 15,  /* watchdogRestart: The firmware restarted after a software watchdog timeout. (MRTM-SAF-004) */
    MRTM_EV_LOG_RECORD_CORRUPT   = 16,  /* logRecordCorrupt: A log record failed its CRC-32 when read. (MRTM-SYS-021) */
    MRTM_EV_LOG_CAPACITY_WARNING = 17,  /* logCapacityWarning: The log reached 9000 records. (MRTM-SYS-022) */
    MRTM_EV_CONFIG_CHANGED       = 18,  /* configChanged: A technician stored a new configuration. (MRTM-SAF-017) */
    MRTM_EV_I2C_BUS_RESET        = 19,  /* i2cBusReset: The I2C bus was reset after a timeout. (MRTM-SAF-021) */
    MRTM_EV_REALARM              = 20,  /* realarm: The buzzer sounded again 15 min after an acknowledgement. (MRTM-SYS-019) */
} mrtm_event_kind_t;

#endif
