#!/usr/bin/env python3
"""Hazard -> risk control -> requirement -> test chain (ISO 14971 §7.2, IEC 62304 §7.3.3).
Reads the `hazard:` field of each safety requirement (what Sanad's safety engine reads) and the
verification matrix Sanad reads (11-verification/cases/verification-cases.csv); optional results
(JUnit XML under 11-verification/results) add the verdict. Sanad has no hazard-to-test view (F-97).
Usage (repo root): python3 tools/hazard-chain.py > 11-verification/hazard-chain.md"""
import csv, glob, json, re, pathlib, xml.etree.ElementTree as ET
ROOT = pathlib.Path(__file__).resolve().parent.parent
haz = {m.group(1): m.group(2).strip() for m in re.finditer(r"\*\*(HAZ-\d+)\*\* ([^|]+)\|", (ROOT / "08-safety/01-risk-analysis.md").read_text())}
ctl = {}
for f in sorted((ROOT / "03-requirements/safety").glob("MRTM-SAF-*.md")):
    t = f.read_text(); m = re.search(r"^hazard: (\[.*\])$", t, re.M)
    title = re.search(r"^# (.*)$", t, re.M)
    for h in json.loads(m.group(1)) if m else []: ctl.setdefault(h, []).append((f.stem, title.group(1) if title else ""))
cases = {}
for r in csv.DictReader(open(ROOT / "11-verification/cases/verification-cases.csv")):
    for rid in r["Verifies"].split(): cases.setdefault(rid, []).append((r["Case"], r["Level"]))
verdict = {}
for x in glob.glob(str(ROOT / "11-verification/results/**/*.xml"), recursive=True):
    for tc in ET.parse(x).getroot().iter("testcase"):
        cid = f"{tc.get('classname')}.{tc.get('name')}" if tc.get("classname") else tc.get("name")
        verdict[cid] = "fail" if tc.find("failure") is not None or tc.find("error") is not None else "blocked" if tc.find("skipped") is not None else "pass"
print("# Hazard → risk control → requirement → test chain — MRTM\n")
print("> **Standard:** ISO 14971 §7.2 (verification of risk-control measures), IEC 62304 §7.3.3 (traceability of risk controls), §5.1.1, Class C.")
print("> **Status:** DRAFT — needs Masood's review. **MANUAL** (F-97): generated by `tools/hazard-chain.py` from the `hazard:` fields Sanad's safety engine reads and the matrix Sanad reads; Sanad shows hazard → requirement (safety engine, `mitigates`) and requirement → case (test-coverage report) but not the whole chain in one view.")
print("> **Plain words:** for each danger, which safety rule stops it, and which tests prove the rule works — and whether they passed.\n")
print("| Hazard | Risk-control requirement | Unit | Integration | System | Verdicts |\n|---|---|---|---|---|---|")
gaps, nopass = [], set()
for h in sorted(haz):
    for rid, title in ctl.get(h, []):
        by = {lv: [c for c, l in cases.get(rid, []) if l == lv] for lv in ("unit", "integration", "system")}
        vs = [verdict.get(c, "no result") for lvl in by.values() for c in lvl]
        summ = ", ".join(f"{v} {vs.count(v)}" for v in ("pass", "fail", "blocked", "no result") if vs.count(v)) or "—"
        if not by["system"]: gaps.append(f"{rid} ({h}) has no system-level case")
        if verdict and "pass" not in vs: nopass.add(rid)
        print(f"| {h} {haz[h]} | {rid} {title} | {len(by['unit'])} | {len(by['integration'])} | {', '.join(by['system']) or '—'} | {summ} |")
print(f"\n**Counts:** {len(haz)} hazards, {sum(len(v) for v in ctl.values())} hazard→control links, "
      f"{len({r for v in ctl.values() for r, _ in v})} risk-control requirements. Gaps: {len(gaps)}"
      + ("".join(f"\n- {g}" for g in gaps) if gaps else " (every control has unit or integration evidence planned and a system procedure).")
      + (f"\n\n**Risk controls with no passing evidence yet** (bench blocked): {', '.join(sorted(nopass))}." if nopass else ""))
