"""Write 06-design/<node-path>/INDEX.md for every node of .ejadah/rew/framework.yaml: the node's pictures in
reading order, its requirement ids, its class. Called by `python3 tools/levels-build.py index`. MANUAL (F-126)."""
import os, pathlib, re, yaml
import fwload  # framework.yaml + tools/levels.yaml (run-local fields, 2026-09-29)
ROOT = pathlib.Path(__file__).resolve().parent.parent
FW = fwload.load()
NODES = {n["name"]: n for n in FW["nodes"]}
ORDER = ["usecases", "blackbox", "whitebox_interconnection", "whitebox_modes", "whitebox_excursion", "whitebox_powerloss", "whitebox_probefault", "leaf"]
WHAT = {"usecases": "who uses the monitor and for what", "blackbox": "the node as ONE box, with the neighbours it is wired to (its promises face outward)",
        "whitebox_interconnection": "inside the node: its parts and their wires, and where the wires leave the node",
        "whitebox_modes": "the modes the monitor moves through", "whitebox_excursion": "scenario: warm air to alarm, subsystem by subsystem",
        "whitebox_powerloss": "scenario: mains lost, battery, backup alarm", "whitebox_probefault": "scenario: the probe stops giving good samples",
        "leaf_states": "the alarm item's state machine (solution detail)", "leaf_classes": "the display item's classes (solution detail)"}

def reqs(n):
    pre = n["prefix"] if isinstance(n["prefix"], list) else [n["prefix"]]
    out = []
    for f in sorted((ROOT / "03-requirements").rglob("MRTM-*.md")):
        if f.stem.rsplit("-", 1)[0] in pre:
            t = f.read_text(); title = re.search(r"^# (.*)$", t, re.M).group(1)
            up = re.search(r"^uplinks: (.*)$", t, re.M).group(1); cls = re.search(r'^safetyClass: "?(\w*)', t, re.M).group(1)
            out.append((f.stem, title, up, cls, f.relative_to(ROOT)))
    return out

def rank(p):
    for i, k in enumerate(ORDER):
        if k in p.stem: return i
    return 99

def main():
    kids = {}
    for n in FW["nodes"]:
        if n.get("parent"): kids.setdefault(n["parent"], []).append(n["name"])
    for n in FW["nodes"]:
        d = ROOT / "06-design" / n["path"]; d.mkdir(parents=True, exist_ok=True)
        pics = sorted((d / "pictures").glob("*.png"), key=rank) if (d / "pictures").exists() else []
        leaf = n["name"] in FW["leaves"]
        role = "leaf — chosen or written, not broken down further" if leaf else "black box, then white box (the MagicGrid step)"
        if n["kind"] == "context": role = "top — the people's needs"
        L = [f"# Node `{n['name']}` — {n.get('title', n['name']).replace('-', ' ')}", "",
             "> MODEL-LEVELS · generated by `tools/levels-build.py index` from `.ejadah/rew/framework.yaml` · DRAFT — needs Masood's review", "",
             "| | |", "|---|---|",
             f"| Kind | {n['kind']} ({FW['node_kinds'][n['kind']]['standard']}) |",
             f"| Role | {role} |",
             f"| IEC 62304 class | **{n['class']}** — reason in each requirement's `## Safety` section and ADR-0034 |",
             f"| Parent | {('`' + n['parent'] + '` → [INDEX](' + os.path.relpath(ROOT / '06-design' / NODES[n['parent']]['path'] / 'INDEX.md', d) + ')') if n.get('parent') else '—'} |",
             f"| Children | {', '.join(f'[`{k}`]({NODES[k]['path'].split('/')[-1]}/INDEX.md)' for k in kids.get(n['name'], [])) or '— (leaf)'} |",
             f"| Units (bottom) | {', '.join(n.get('units', [])) or '—'} |", "",
             "## Pictures, in reading order", ""]
        if not pics: L.append("_None: a leaf is described by its requirements and its chosen part or unit; its detail pictures sit with the item that owns them._")
        for i, p in enumerate(pics, 1):
            key = next((k for k in WHAT if k in p.stem), "")
            L += [f"{i}. **`{p.stem}`** — {WHAT.get(key, '')}", "", f"   ![{p.stem}](pictures/{p.name})", ""]
        rs = reqs(n)
        L += ["", f"## Requirements this node satisfies ({len(rs)}) — and nothing else", "",
              "| Id | Title | Derived from (parent node) | Class |", "|---|---|---|---|"]
        L += [f"| [{r}]({os.path.relpath(ROOT / p, d)}) | {t} | {u} | {c} |" for r, t, u, c, p in rs]
        model = sorted(x.name for x in d.glob("*.sysml"))
        L += ["", "## Model files", "", ", ".join(f"`{m}`" for m in model), ""]
        (d / "INDEX.md").write_text("\n".join(L))
    print(f"index: {len(FW['nodes'])} INDEX.md written")

def story():
    """06-design/DECOMPOSITION.md — the whole tree on one page: the decomposition story."""
    kids = {}
    for n in FW["nodes"]:
        if n.get("parent"): kids.setdefault(n["parent"], []).append(n["name"])
    L = ["# The decomposition story — read this first", "",
         "> MODEL-LEVELS · generated by `python3 tools/levels-build.py index` · framework: `.ejadah/rew/framework.yaml` (MagicGrid default, medical flavour) · DRAFT — needs Masood's review", "",
         "**How to read it:** start at the top. Each box is looked at twice — from outside (black box: what it must do) and from inside (white box: which smaller boxes do it). "
         "Each smaller box then gets the same two looks, until a box is simple enough to buy or to code (a leaf). Like opening Russian dolls one at a time. "
         "Every picture shows ONE node, and every node satisfies ONLY its own requirements.", "",
         "| Node (indent = depth) | Kind | Class | Requirements | Pictures |", "|---|---|---|---|---|"]
    def walk(name, depth):
        n = NODES[name]; d = ROOT / "06-design" / n["path"]
        pics = len(list((d / "pictures").glob("*.png"))) if (d / "pictures").exists() else 0
        leaf = " (leaf)" if name in FW["leaves"] else ""
        L.append(f"| {'&nbsp;&nbsp;&nbsp;&nbsp;' * depth}[{name}]({n['path']}/INDEX.md){leaf} | {n['kind']} | {n['class']} | {len(reqs(n))} | {pics} |")
        for k in kids.get(name, []): walk(k, depth + 1)
    walk("context", 0)
    L += ["", "Checked by `python3 tools/level-check.py` (own-node-only satisfy, derive chain to the top, ≤ 12 boxes a picture, INDEX per node).", ""]
    (ROOT / "06-design/DECOMPOSITION.md").write_text("\n".join(L))

_main = main
def main():
    _main(); story()
