#!/usr/bin/env python3
"""RUN-05: writes one SysML v2 package per node of .ejadah/rew/framework.yaml (pinned IEC 62304 stack) into
06-design/<node-path>/, plus one view package per picture (package-level parts the canvas can place, F-129).
The structure is written below as SysML text (MANUAL, F-127); the `satisfy` lines are generated from the
requirement files: a node satisfies ITS OWN requirements only. Usage (run folder): python3 tools/pinned_model.py.
DRAFT — needs Masood's review."""
import pathlib, yaml
ROOT = pathlib.Path(__file__).resolve().parent.parent
FW = yaml.safe_load((ROOT / ".ejadah/rew/framework.yaml").read_text())
NODES = {n["name"]: n for n in FW["nodes"]}
D = ROOT / "06-design"

def camel(s):
    if "-" not in s: return s[0].lower() + s[1:]
    w = s.split("-"); return w[0] + "".join(x.capitalize() for x in w[1:])
def pascal(s): return "".join(x.capitalize() for x in s.split("-"))

def ids_of(node):
    pre = NODES[node]["prefix"]; pre = pre if isinstance(pre, list) else [pre]
    return sorted(f.stem for f in (ROOT / "03-requirements").rglob("MRTM-*.md") if f.stem.rsplit("-", 1)[0] in pre)

def put(rel, text): p = D / rel; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text); return p

def package(rel, name, imports, doc, body, head):
    return put(rel, f"// {name} — {head} Generated by tools/pinned_model.py — edit there. RUN-05.\n"
               + "private import ScalarValues::*;\n" + "".join(f"private import {i}::*;\n" for i in imports)
               + f"\npackage {name} {{\n\n    doc /* {doc} */\n{body}}}\n")

def node_file(node, imports, doc, body, by):
    n = NODES[node]; ids = ids_of(node)
    sat = "".join(f"    satisfy '{i}' by {by};\n" for i in ids)
    package(f"{n['path']}/Node{pascal(node)}.sysml", f"Node{pascal(node)}", ["ProjectRequirements"] + imports, doc, body + "\n" + sat,
            f"node `{node}` (level {n['level']}, {n['kind']}, IEC 62304 class {n['class']}); satisfies ONLY its own {len(ids)} requirements.")
    return len(ids)

# ---------------- vocabulary: the flows between items and the people at the device ----------------
VOCAB = """
    // Flows between software items (what crosses an item boundary).
    port def SampleFlow { out item sample : TemperatureSample; }
    port def ExcursionFlow { out item excursion : ExcursionState; }
    port def AlarmStateFlow { out item alarmState : ExcursionState; }
    port def RecordFlow { out item rec : LogRecord; }
    port def PowerEventFlow { out item evt : PowerEvent; }
    port def HeartbeatFlow { out attribute beat : Natural; }
    port def HistoryFlow { out item file : LogFile; }
    port def BandFlow { out attribute lowTenths : Integer; out attribute highTenths : Integer; }
    port def TimeFlow { out attribute utcS : Natural; }
    // What people meet at the device: the alarm signals (sound, light, button) and the screen.
    port def AlarmHmiPort { out item signal : AlarmCommand; in item press : ButtonPress; }
    port def ScreenPort { out item screenFrame : DisplayFrame; }
    // Everything the software drives or reads on the hardware, bundled as one port (the hardware abstraction layer, HAL).
    port def HalPort { port probeBus : OneWirePort; port buzzerDrive : GpioOutPort; port lightDrive : GpioOutPort; port button : GpioInPort;
        port displayBus : I2cPort; port clockBus : I2cPort; port usbData : UsbPort; port mainsSense : GpioInPort; port batterySense : ~PowerPort; port kick : GpioOutPort; }
    // The people at the device (nurse, pharmacist, manager, technician).
    part def Staff { port alarmSignals : ~AlarmHmiPort; port screen : ~ScreenPort; }
"""
VI = ["MrtmInterfaces", "LevelPorts"]

# the software <-> hardware signals: (port on SoftwareSystem, type on the software side)
HAL = [("probeBus", "OneWirePort"), ("buzzerDrive", "GpioOutPort"), ("lightDrive", "GpioOutPort"), ("button", "GpioInPort"),
       ("displayBus", "I2cPort"), ("clockBus", "I2cPort"), ("usbData", "UsbPort"), ("mainsSense", "GpioInPort"),
       ("batterySense", "~PowerPort"), ("kick", "GpioOutPort")]
def conj(t): return t[1:] if t.startswith("~") else "~" + t
OUTSIDE = [("air", "~ThermalPort"), ("mains", "~PowerPort"), ("usb", "UsbPort"), ("alarmSignals", "AlarmHmiPort"), ("screen", "ScreenPort")]

# ---------------- level 3 items: def name, library base, ports, units ----------------
ITEMS = {
 "sensor-item":     ("SensorSwItem", "SensorItem", ["bus : OneWirePort", "samples : SampleFlow"], ["sensor-sampler"]),
 "excursion-item":  ("ExcursionSwItem", "ExcursionItem", ["samples : ~SampleFlow", "excursion : ExcursionFlow", "band : ~BandFlow"], ["limit-evaluator"]),
 "alarm-item":      ("AlarmSwItem", "AlarmItem", ["excursion : ~ExcursionFlow", "alarmState : AlarmStateFlow", "records : RecordFlow", "powerEvents : ~PowerEventFlow",
                     "heartbeat : HeartbeatFlow", "buzzerDrive : GpioOutPort", "lightDrive : GpioOutPort", "button : GpioInPort"], ["alarm-mgr"]),
 "display-item":    ("DisplaySwItem", "DisplayItem", ["samples : ~SampleFlow", "alarmState : ~AlarmStateFlow", "i2c : I2cPort"], ["display-mgr"]),
 "log-item":        ("LogSwItem", "LogItem", ["records : ~RecordFlow", "clock : I2cPort", "history : HistoryFlow"], ["event-log", "history-ring", "rtc-clock"]),
 "usb-item":        ("UsbSwItem", "UsbItem", ["history : ~HistoryFlow", "usb : UsbPort"], ["usb-export"]),
 "power-item":      ("PowerSwItem", "PowerItem", ["mainsSense : GpioInPort", "batterySense : ~PowerPort", "events : PowerEventFlow", "records : RecordFlow"], ["power-mon"]),
 "supervisor-item": ("SupervisorSwItem", "SupervisorItem", ["heartbeat : ~HeartbeatFlow", "pulses : GpioOutPort", "records : RecordFlow", "band : BandFlow"],
                     ["wdt-kicker", "diagnostics", "config-mgr"]),
}
# ---------------- level 4 units: def name, library base, extra ports, library usage name inside the item ----------------
UNITS = {
 "sensor-sampler":  ("SensorSamplerUnit", "SensorSampler", ["bus : OneWirePort"], "sensorSampler"),
 "limit-evaluator": ("LimitEvaluatorUnit", "LimitEvaluator", ["band : ~BandFlow"], "limitEvaluator"),
 "alarm-mgr":       ("AlarmMgrUnit", "AlarmMgr", ["powerEvents : ~PowerEventFlow", "buzzerDrive : GpioOutPort", "lightDrive : GpioOutPort", "button : GpioInPort"], "alarmMgr"),
 "display-mgr":     ("DisplayMgrUnit", "DisplayMgr", ["samples : ~SampleFlow", "i2c : I2cPort"], "displayMgr"),
 "event-log":       ("EventLogUnit", "EventLog", ["toRing : RecordFlow", "clock : ~TimeFlow"], "eventLog"),
 "history-ring":    ("HistoryRingUnit", "HistoryRingStore", ["append : ~RecordFlow", "history : HistoryFlow"], "historyRing"),
 "rtc-clock":       ("RtcClockUnit", "RtcClock", ["i2c : I2cPort", "now : TimeFlow"], "rtcClock"),
 "usb-export":      ("UsbExportUnit", "UsbExport", ["history : ~HistoryFlow", "usb : UsbPort"], "usbExport"),
 "power-mon":       ("PowerMonUnit", "PowerMon", ["mainsSense : GpioInPort", "batterySense : ~PowerPort", "events : PowerEventFlow"], "powerMon"),
 "wdt-kicker":      ("WdtKickerUnit", "WdtKicker", ["pulses : GpioOutPort"], "wdtKicker"),
 "diagnostics":     ("DiagnosticsUnit", "Diagnostics", [], "diagnostics"),
 "config-mgr":      ("ConfigMgrUnit", "ConfigMgr", ["band : BandFlow"], "configMgr"),
}
# item structure views: neighbour stubs {name: [ (port, type) ]} and wires (a, b) between unit ports and stub ports
ITEM_VIEW = {
 "sensor-item": ({"hardwareItem": [("probeBus", "~OneWirePort")], "excursionItem": [("samples", "~SampleFlow")], "displayItem": [("samples", "~SampleFlow")]},
                 [("sensorSampler.bus", "hardwareItem.probeBus"), ("sensorSampler.samples", "excursionItem.samples"), ("sensorSampler.samples", "displayItem.samples")]),
 "excursion-item": ({"sensorItem": [("samples", "SampleFlow")], "alarmItem": [("excursion", "~ExcursionFlow")], "supervisorItem": [("band", "BandFlow")]},
                 [("sensorItem.samples", "limitEvaluator.samples"), ("limitEvaluator.excursion", "alarmItem.excursion"), ("supervisorItem.band", "limitEvaluator.band")]),
 "alarm-item": ({"excursionItem": [("excursion", "ExcursionFlow")], "displayItem": [("alarmState", "~AlarmStateFlow")], "logItem": [("records", "~RecordFlow")],
                 "powerItem": [("events", "PowerEventFlow")], "supervisorItem": [("heartbeat", "~HeartbeatFlow")],
                 "hardwareItem": [("buzzerDrive", "~GpioOutPort"), ("lightDrive", "~GpioOutPort"), ("button", "~GpioInPort")]},
                [("excursionItem.excursion", "alarmMgr.excursion"), ("alarmMgr.alarm", "displayItem.alarmState"), ("alarmMgr.log", "logItem.records"),
                 ("powerItem.events", "alarmMgr.powerEvents"), ("alarmMgr.heartbeat", "supervisorItem.heartbeat"), ("alarmMgr.buzzerDrive", "hardwareItem.buzzerDrive"),
                 ("alarmMgr.lightDrive", "hardwareItem.lightDrive"), ("hardwareItem.button", "alarmMgr.button")]),
 "display-item": ({"sensorItem": [("samples", "SampleFlow")], "alarmItem": [("alarmState", "AlarmStateFlow")], "hardwareItem": [("displayBus", "~I2cPort")]},
                 [("sensorItem.samples", "displayMgr.samples"), ("alarmItem.alarmState", "displayMgr.alarm"), ("displayMgr.i2c", "hardwareItem.displayBus")]),
 "log-item": ({"alarmItem": [("records", "RecordFlow")], "powerItem": [("records", "RecordFlow")], "supervisorItem": [("records", "RecordFlow")],
               "usbItem": [("history", "~HistoryFlow")], "hardwareItem": [("clockBus", "~I2cPort")]},
              [("alarmItem.records", "eventLog.records"), ("powerItem.records", "eventLog.records"), ("supervisorItem.records", "eventLog.records"),
               ("eventLog.toRing", "historyRing.append"), ("rtcClock.now", "eventLog.clock"), ("rtcClock.i2c", "hardwareItem.clockBus"), ("historyRing.history", "usbItem.history")]),
 "usb-item": ({"logItem": [("history", "HistoryFlow")], "hardwareItem": [("usbData", "~UsbPort")]},
              [("logItem.history", "usbExport.history"), ("usbExport.usb", "hardwareItem.usbData")]),
 "power-item": ({"hardwareItem": [("mainsSense", "~GpioInPort"), ("batterySense", "PowerPort")], "alarmItem": [("powerEvents", "~PowerEventFlow")], "logItem": [("records", "~RecordFlow")]},
                [("hardwareItem.mainsSense", "powerMon.mainsSense"), ("hardwareItem.batterySense", "powerMon.batterySense"), ("powerMon.events", "alarmItem.powerEvents"), ("powerMon.log", "logItem.records")]),
 "supervisor-item": ({"alarmItem": [("heartbeat", "HeartbeatFlow")], "hardwareItem": [("kick", "~GpioOutPort")], "logItem": [("records", "~RecordFlow")], "excursionItem": [("band", "~BandFlow")]},
                     [("alarmItem.heartbeat", "wdtKicker.heartbeat"), ("wdtKicker.pulses", "hardwareItem.kick"), ("diagnostics.log", "logItem.records"), ("configMgr.band", "excursionItem.band")]),
}
ARCH_WIRES = [("sensorItem.samples", "excursionItem.samples"), ("sensorItem.samples", "displayItem.samples"), ("excursionItem.excursion", "alarmItem.excursion"),
              ("alarmItem.alarmState", "displayItem.alarmState"), ("alarmItem.records", "logItem.records"), ("powerItem.records", "logItem.records"),
              ("supervisorItem.records", "logItem.records"), ("powerItem.events", "alarmItem.powerEvents"), ("alarmItem.heartbeat", "supervisorItem.heartbeat"),
              ("supervisorItem.band", "excursionItem.band"), ("logItem.history", "usbItem.history")]
HAL_WIRES = [("sensorItem.bus", "hardwareItem.probeBus"), ("alarmItem.buzzerDrive", "hardwareItem.buzzerDrive"), ("alarmItem.lightDrive", "hardwareItem.lightDrive"),
             ("hardwareItem.button", "alarmItem.button"), ("displayItem.i2c", "hardwareItem.displayBus"), ("logItem.clock", "hardwareItem.clockBus"),
             ("usbItem.usb", "hardwareItem.usbData"), ("hardwareItem.mainsSense", "powerItem.mainsSense"), ("hardwareItem.batterySense", "powerItem.batterySense"),
             ("supervisorItem.pulses", "hardwareItem.kick")]
HW_PARTS = [("mcu", "Esp32S3Module"), ("probe", "Ds18b20"), ("buzzer", "PiezoBuzzerStage"), ("redLed", "IndicatorLed"), ("ackButton", "TactileButton"),
            ("oled", "Oled128x64"), ("rtc", "TcxoRtc"), ("backupTimer", "WatchdogAlarmTimer"), ("holdUp", "Supercap"), ("battery", "LiIonCell"), ("powerPath", "ChargerPowerPath")]
HW_WIRES = [("mcu.oneWire", "probe.dq"), ("mcu.buzzerPin", "buzzer.drive"), ("mcu.redPin", "redLed.drive"), ("ackButton.contact", "mcu.ackPin"),
            ("mcu.i2c", "oled.i2c"), ("mcu.i2c", "rtc.i2c"), ("mcu.wdtKickPin", "backupTimer.kick"), ("backupTimer.alarmOut", "buzzer.backupDrive"),
            ("holdUp.terminal", "backupTimer.holdUp"), ("battery.terminal", "powerPath.batteryIn"), ("powerPath.output", "mcu.supply"), ("powerPath.output", "holdUp.charge")]

def conns(ws): return "".join(f"    connect {a} to {b};\n" for a, b in ws)
def stub(n, ports, note): return f"    part {n} {{ " + " ".join(f"port {p} : {t};" for p, t in ports) + f" }}  // {note}\n"

def main():
    sat = 0
    put("L1-device/LevelPorts.sysml", "// LevelPorts — the words every level uses for what crosses a boundary. RUN-05.\nprivate import ScalarValues::*;\n"
        "private import MrtmInterfaces::*;\n\npackage LevelPorts {\n" + VOCAB + "}\n")
    item_pkgs = [f"Node{pascal(i)}" for i in ITEMS]
    unit_pkgs = [f"Node{pascal(u)}" for u in UNITS]
    # ---- L1 device ----
    body = "\n    part def MedicalDevice {\n        doc /* Black box: the medical device (IEC 60601-1 PEMS) as the clinic meets it. */\n" \
        + "".join(f"        port {p} : {t};\n" for p, t in OUTSIDE) + "    }\n" \
        + "    part def DeviceWhiteBox :> MedicalDevice {\n        doc /* White box: ONE hardware item and ONE software system, pinned by IEC 62304 (the software system runs on the hardware item). Wires: package NodeDeviceWhiteBox. */\n" \
        + "        part hardwareItem : HardwareItem;\n        part softwareSystem : SoftwareSystem;\n    }\n    part device : MedicalDevice;\n"
    sat += node_file("device", VI + ["NodeHardwareItem", "NodeSoftwareSystem"],
                     "LEVEL 1 — DEVICE (IEC 60601-1 PEMS; ISO 14971 risk management file 08-safety/). Satisfies the stakeholder and device requirements only.", body, "device")
    package("L1-device/NodeDeviceContext.sysml", "NodeDeviceContext", VI + ["MrtmSystemContext", "NodeDevice"],
            "Device context: the device as ONE box among the people and things it touches.",
            "    part fridge : Fridge;\n    part device : MedicalDevice;\n    part mains : MainsSupply;\n    part usbHost : UsbHost;\n    part staff : Staff;\n"
            + conns([("fridge.air", "device.air"), ("mains.output", "device.mains"), ("device.usb", "usbHost.usb"), ("device.alarmSignals", "staff.alarmSignals"), ("device.screen", "staff.screen")]),
            "the device and its neighbours (view package, no satisfy).")
    package("L1-device/NodeDeviceWhiteBox.sysml", "NodeDeviceWhiteBox", VI + ["MrtmSystemContext", "NodeHardwareItem", "NodeSoftwareSystem"],
            "Device block: the hardware item and the software system, and the neighbours the device boundary meets.",
            "    part hardwareItem : HardwareItem;\n    part softwareSystem : SoftwareSystem;\n    part fridge : Fridge;\n    part mains : MainsSupply;\n    part usbHost : UsbHost;\n    part staff : Staff;\n"
            + conns([("fridge.air", "hardwareItem.air"), ("mains.output", "hardwareItem.mains"), ("hardwareItem.usb", "usbHost.usb"),
                     ("hardwareItem.alarmSignals", "staff.alarmSignals"), ("hardwareItem.screen", "staff.screen")]
                    + [("softwareSystem.hal", "hardwareItem.hal")]),
            "white box of the device in its context (view package, no satisfy).")
    # ---- L2 hardware item ----
    body = "\n    part def HardwareItem {\n        doc /* The hardware side as ONE item under the device (IEC 60601-1 cl. 4.8 components, cl. 14.8). Outside ports + the signals the software uses. */\n" \
        + "".join(f"        port {p} : {t};\n" for p, t in OUTSIDE) + "        port hal : ~HalPort;\n    }\n" \
        + "    part def HardwareItemWhiteBox :> HardwareItem {\n        doc /* The chosen parts (09-hardware/). Wires: package NodeHardwareItemParts. */\n" \
        + "".join(f"        part {n} : MrtmHardware::{t};\n" for n, t in HW_PARTS) + "    }\n    part hardwareItem : HardwareItem;\n"
    sat += node_file("hardware-item", VI + ["MrtmHardware"], "LEVEL 2 — HARDWARE ITEM (class C risk controls in hardware: backup alarm, buzzer, probe).", body, "hardwareItem")
    package("L2-hardware-item/NodeHardwareItemParts.sysml", "NodeHardwareItemParts", VI + ["MrtmHardware"],
            "Inside the hardware item: the chosen parts and their wires.",
            "".join(f"    part {n} : {t};\n" for n, t in HW_PARTS) + conns(HW_WIRES), "parts of the hardware item (view package, no satisfy).")
    # ---- L2 software system ----
    body = "\n    part def SoftwareSystem {\n        doc /* IEC 62304 software system, class C: the firmware on the hardware item's processor. Its ports are the signals it drives and reads. */\n" \
        + "        attribute safetyClass : MrtmSoftware::SafetyClass = MrtmSoftware::SafetyClass::C;\n" \
        + "        port hal : HalPort;\n    }\n" \
        + "    part def SoftwareSystemWhiteBox :> SoftwareSystem {\n        doc /* IEC 62304 §5.3.1: the eight software items. Wires: packages NodeSoftwareSystemArchitecture and NodeSoftwareSystemHardwareInterface. */\n" \
        + "".join(f"        part {camel(i)} : {d};\n" for i, (d, *_) in ITEMS.items()) + "    }\n    part softwareSystem : SoftwareSystem;\n"
    sat += node_file("software-system", VI + ["MrtmSoftware"] + item_pkgs, "LEVEL 2 — SOFTWARE SYSTEM (IEC 62304 §5.2 SRS, §5.3 architecture). Satisfies the SRS only.", body, "softwareSystem")
    items_parts = "".join(f"    part {camel(i)} : {d};\n" for i, (d, *_) in ITEMS.items())
    package("L2-software-system/NodeSoftwareSystemArchitecture.sysml", "NodeSoftwareSystemArchitecture", VI + ["MrtmSoftware"] + item_pkgs,
            "Software architecture (IEC 62304 §5.3.1–5.3.2): the eight items and the flows between them. Class B item: usbItem (segregated, ADR-0034).",
            items_parts + conns(ARCH_WIRES), "items and their flows (view package, no satisfy).")
    package("L2-software-system/NodeSoftwareSystemHardwareInterface.sysml", "NodeSoftwareSystemHardwareInterface", VI + ["MrtmSoftware", "NodeHardwareItem"] + item_pkgs,
            "Software to hardware (IEC 62304 §5.3.3/§5.3.4 hardware the software needs): which item drives or reads which hardware signal.",
            items_parts + stub("hardwareItem", [(p, conj(t)) for p, t in HAL], "the hardware item, shown by the signals inside its hal port") + conns(HAL_WIRES), "items and the hardware item (view package, no satisfy).")
    seq = [("hardwareItem", "HardwareItem"), ("sensorItem", "SensorSwItem"), ("excursionItem", "ExcursionSwItem"), ("alarmItem", "AlarmSwItem"),
           ("displayItem", "DisplaySwItem"), ("logItem", "LogSwItem")]
    msgs = [("sample", "TemperatureSample", "hardwareItem", "sensorItem"), ("validSample", "TemperatureSample", "sensorItem", "excursionItem"),
            ("early", "ExcursionState", "excursionItem", "alarmItem"), ("redFlash", "AlarmCommand", "alarmItem", "hardwareItem"),
            ("confirmed", "ExcursionState", "excursionItem", "alarmItem"), ("buzzerOn", "AlarmCommand", "alarmItem", "hardwareItem"),
            ("warning", "ExcursionState", "alarmItem", "displayItem"), ("startRecord", "LogRecord", "alarmItem", "logItem")]
    package("L2-software-system/L2SeqExcursion.sysml", "L2SeqExcursion", VI + ["NodeHardwareItem"] + item_pkgs,
            "Excursion scenario at item level: first out-of-band sample -> low-priority light within 5 s -> confirmation after 31 samples (60 s) -> buzzer, warning, record.",
            "".join(f"    part {n} : {t};\n" for n, t in seq) + "".join(f"    message {m} of {t} from {a} to {b};\n" for m, t, a, b in msgs)
            + "".join(f"    succession first {a[0]} then {b[0]};\n" for a, b in zip(msgs, msgs[1:])),
            "item-level excursion sequence (view package, no satisfy).")
    # ---- L3 items ----
    for item, (dn, base, ports, units) in ITEMS.items():
        n = NODES[item]
        cls = ""  # class B is set on the library defs UsbItem / UsbExport (ruling A-48)
        seg = f" Segregation (§5.3.5): {n['segregation']}." if n.get("segregation") else ""
        body = f"\n    #Service part def {dn} :> {base} {{\n        doc /* IEC 62304 software item, class {n['class']}.{seg} Units: {', '.join(units)}. */{cls}\n" \
            + "".join(f"        port {p};\n" for p in ports) + "    }\n" + f"    part {camel(dn)} : {dn};\n"
        sat += node_file(item, VI + ["MrtmSoftware", "SoftwareProfile"], f"LEVEL 3 — SOFTWARE ITEM `{item}` (IEC 62304 §5.3; class {n['class']}).", body, camel(dn))
        stubs, wires = ITEM_VIEW[item]
        uparts = "".join(f"    part {UNITS[u][3]} : {UNITS[u][0]};\n" for u in units)
        package(f"{n['path']}/Node{pascal(item)}Structure.sysml", f"Node{pascal(item)}Structure", VI + ["MrtmSoftware"] + [f"Node{pascal(u)}" for u in units],
                f"Inside item {item}: its units, and the neighbours its boundary ports meet (each shown by the shared ports only).",
                uparts + "".join(stub(s, p, "neighbour, shared ports only") for s, p in stubs.items()) + conns(wires),
                f"internal structure of item `{item}` (view package, no satisfy).")
    # ---- L4 units ----
    for unit, (dn, base, ports, _) in UNITS.items():
        n = NODES[unit]
        cls = ""  # class B is set on the library defs UsbItem / UsbExport (ruling A-48)
        api = "".join(w.capitalize() for w in unit.split("-")).replace("HistoryRing", "HistoryRing") + "Api"
        body = f"\n    #Component part def {dn} :> {base} {{\n        doc /* IEC 62304 software unit (§5.4.1), class {n['class']} (its item `{n['parent']}`). Code: 10-src/firmware/components/{n['code']}/. " \
            f"Contract (§5.4.2/§5.4.3): MrtmSwDetail::{api} and contracts.md. */{cls}\n" + "".join(f"        port {p};\n" for p in ports) + "    }\n" + f"    part {camel(dn)} : {dn};\n"
        sat += node_file(unit, VI + ["MrtmSoftware", "SoftwareProfile"], f"LEVEL 4 — SOFTWARE UNIT `{unit}` (IEC 62304 §5.4/§5.5; class {n['class']}).", body, camel(dn))
    print(f"nodes: {len(NODES)}, satisfy lines: {sat}")

if __name__ == "__main__":
    main()
