"""MODEL-LEVELS data: the requirements of every node below the system, in the order Sanad's allocator
numbers them. Read by tools/levels-build.py. Each row:
  id (the id the allocator is expected to give; the build refuses if it gives another), parents (ids of the
  PARENT node only), title, statement, rationale (with its source line), verification,
  impl  = [(C file under 10-src/firmware/components, line of an existing @implements marker)],
  ver   = [(test file under 10-src, test function)] or ["SP-nn"] (system procedure rows).
Hardware leaves carry no impl. DRAFT — needs Masood's review."""

SRC_WHO = "source: WHO PQS E006 / CDC Vaccine Storage and Handling Toolkit (assumed sources, edition and clause to confirm)"
SRC_1_8 = "source: IEC 60601-1-8 (edition assumed :2006+A1:2012+A2:2020, to be confirmed against the customer's edition)"

A, E, L, U = "alarm_mgr/src/alarm_mgr.c", "limit_evaluator/src/limit_evaluator.c", "event_log/src/event_log.c", "usb_export/src/usb_export.c"
TA, TE = "firmware/components/alarm_mgr/test/test_alarm_mgr.c", "firmware/components/limit_evaluator/test/test_limit_evaluator.c"
TI = "test/integration/test_int_chains.c"

REQS = [
 # ---------------- sensing (subsystem) ----------------
 ("MRTM-SEN-001", ["MRTM-SYS-001"], "Sensing sample period",
  "The sensing subsystem shall deliver one fridge air temperature sample every 2 s.",
  "Allocates the system sampling period to the subsystem that owns the probe. The 2 s figure is ADR-0031; " + SRC_WHO + ".",
  "Test: SP-01 bench trace of sample time stamps; unit tests of the sensor item.", [], ["SP-01"]),
 ("MRTM-SEN-002", ["MRTM-SYS-024"], "Sensing sample latency",
  "The sensing subsystem shall deliver each sample within 750 ms of the start of its conversion.",
  "The sensing share of the 5 s early-alarm budget: 2 s wait + 750 ms conversion; the alarm subsystem holds the remaining 1 s (ADR-0030). 750 ms is the 12-bit conversion time of the chosen probe class (A-40).",
  "Test: unit test of the budget sum; SP-01.11 timed trials.", [], [(TE, "test_early_alarm_budget_fits_5_s")]),
 ("MRTM-SEN-003", ["MRTM-PRF-001", "MRTM-ENV-004"], "Sensing accuracy",
  "The sensing subsystem shall measure the fridge air temperature with an accuracy of ±0.5 °C over the range 0 °C to 15 °C.",
  "Carries the system accuracy down unchanged: the probe is the only measuring part. " + SRC_WHO + ".",
  "Test: SP-10 at 0, 2, 5, 8, 15 °C against a reference thermometer.", [], ["SP-10"]),
 ("MRTM-SEN-004", ["MRTM-SYS-012", "MRTM-SAF-003"], "Sensing invalid sample",
  "The sensing subsystem shall mark a sample invalid when its CRC-8 check fails or its value is outside -30 °C to 50 °C.",
  "An invalid sample must never count toward an excursion or its end (A-29); the probe fault timer counts invalid samples.",
  "Test: unit tests of the sensor item; SP-02.", [], ["SP-02"]),
 ("MRTM-PRB-001", ["MRTM-SEN-002"], "Probe conversion time",
  "The probe shall complete a 12-bit temperature conversion within 750 ms.",
  "Chosen part class: 1-Wire digital probe (ADR-0009, ADR-0015). Figure from the part class, synthetic (A-40).",
  "Inspection of the part data; SP-10 bus capture.", [], ["SP-10"]),
 ("MRTM-PRB-002", ["MRTM-SEN-003"], "Probe accuracy",
  "The probe shall read the air temperature with an accuracy of ±0.5 °C from -10 °C to 50 °C.",
  "The sensing accuracy is all probe: the firmware only converts units (A-40).",
  "Test: SP-10.", [], ["SP-10"]),
 ("MRTM-PRB-003", ["MRTM-SEN-004"], "Probe scratchpad check",
  "The probe shall send a CRC-8 value with every scratchpad read.",
  "The CRC-8 is what lets the sensor item tell a bad read from a real temperature (ADR-0009).",
  "Inspection of a bus capture in SP-10.", [], ["SP-10"]),
 ("MRTM-SNI-001", ["MRTM-SEN-001", "MRTM-SEN-002"], "Sensor item conversion start",
  "The sensor item shall start one probe conversion every 2 s and read the scratchpad 750 ms after the start.",
  "The software half of the sensing period and latency; runs in the sensor task (ADR-0019).",
  "Test: unit tests of sensor_sampler.",
  [("sensor_sampler/src/sensor_sampler.c", 37)], [("firmware/components/sensor_sampler/test/test_sensor_sampler.c", "test_good_scratchpad_gives_a_valid_sample")]),
 ("MRTM-SNI-002", ["MRTM-SEN-004"], "Sensor item invalid sample",
  "The sensor item shall mark the sample invalid when the scratchpad CRC-8 fails or the value is outside -30 °C to 50 °C.",
  "Detects the probe faults of HAZ-001 and HAZ-004 at the first bad read.",
  "Test: unit tests of sensor_sampler.",
  [("sensor_sampler/src/sensor_sampler.c", 62)],
  [("firmware/components/sensor_sampler/test/test_sensor_sampler.c", "test_bad_crc_is_invalid_but_not_out_of_range"),
   ("firmware/components/sensor_sampler/test/test_sensor_sampler.c", "test_reading_outside_minus30_to_50_declares_the_fault_at_once")]),
 # ---------------- alarm-and-indication (subsystem) ----------------
 ("MRTM-ALM-001", ["MRTM-SYS-024"], "Alarm early signal latency",
  "The alarm subsystem shall show the low-priority excursion alarm signal within 1 s of the first valid out-of-band sample.",
  "The alarm share of the 5 s early-alarm budget (sensing 2.75 s + alarm 1 s = 3.75 s, ADR-0030). Low priority in the sense of IEC 60601-1-8; " + SRC_1_8 + ".",
  "Test: unit test of the budget sum; unit test of the early state; SP-01.11.", [],
  [(TE, "test_early_alarm_budget_fits_5_s"), (TA, "test_early_alarm_is_red_1_hz_without_buzzer_then_escalates")]),
 ("MRTM-ALM-002", ["MRTM-SYS-002"], "Alarm excursion confirmation",
  "The alarm subsystem shall confirm the excursion when 31 consecutive valid samples are outside the allowed band.",
  "31 samples at 2 s span 60 s: the door-opening filter of STK-002 (ADR-0031). 60 s is assumption A-04; " + SRC_WHO + ".",
  "Test: unit tests of limit_evaluator; integration INT-01.", [],
  [(TE, "test_early_alarm_budget_fits_5_s"), (TI, "test_int01_excursion_chain")]),
 ("MRTM-ALM-003", ["MRTM-SYS-003", "MRTM-PRF-002"], "Alarm buzzer latency",
  "The alarm subsystem shall sound the buzzer within 1 s of excursion confirmation.",
  "The software share of the 5 s confirmation-to-buzzer budget is one 1 s alarm cycle (ADR-0020); the rest is margin.",
  "Test: unit test of the alarm item; integration INT-01.", [], [(TI, "test_int01_excursion_chain")]),
 ("MRTM-ALM-004", ["MRTM-SYS-006", "MRTM-IFC-002"], "Alarm acknowledge",
  "The alarm subsystem shall stop the buzzer within 1 s of a debounced acknowledge press.",
  "Carries SYS-006 down; the 50 ms debounce of IFC-002 sits inside the 1 s.",
  "Test: unit tests of the alarm item.", [], [(TA, "test_ack_stops_the_buzzer_in_the_same_step_and_logs")]),
 ("MRTM-ALM-005", ["MRTM-SAF-009", "MRTM-SAF-010"], "Alarm backup path",
  "The alarm subsystem shall sound the buzzer from the backup alarm within 10 s of the last watchdog service pulse.",
  "Risk control of HAZ-003 (firmware hang), independent of the processor (ADR-0013).",
  "Test: integration INT-02; SP-03.", [], [(TI, "test_int02_watchdog_chain"), "SP-03"]),
 ("MRTM-ALM-006", ["MRTM-SYS-003"], "Alarm high-priority auditory pattern",
  "The alarm subsystem shall sound the confirmed excursion alarm as bursts of 10 pulses with a burst repetition interval from 2.5 s to 15 s.",
  "Derived from the standard, not from a stakeholder: IEC 60601-1-8 high-priority auditory alarm signal (§6.3.3, table 3); " + SRC_1_8 + ". The design today sounds a continuous tone (SYS-003 as built) — delta D-2 in 13-assessment/iec60601-1-8-check.md. NOT YET DECOMPOSED OR IMPLEMENTED: owner decision Q-20.",
  "Test (planned): SP-06 with a sound recorder; pulse count and interval.", [], []),
 ("MRTM-ALM-007", ["MRTM-SYS-018"], "Alarm excursion end",
  "The alarm subsystem shall end the excursion after 31 consecutive valid samples inside the allowed band.",
  "Symmetric with ALM-002, so a sensor reading near the edge does not toggle the alarm (ADR-0031).",
  "Test: unit tests of limit_evaluator.", [], [(TE, "test_nth_consecutive_in_sample_ends_excursion")]),
 ("MRTM-ALM-008", ["MRTM-SAF-013"], "Alarm backup hold-up",
  "The alarm subsystem shall sound the backup alarm for 60 s or more after the loss of both mains and battery power.",
  "Risk control of HAZ-005: the last warning when all power is gone (ADR-0013). 60 s is assumption A-18.",
  "Test: SP-03 with both supplies removed.", [], ["SP-03"]),
 ("MRTM-EXI-001", ["MRTM-ALM-001"], "Excursion item early report",
  "The excursion item shall report the early excursion at the first valid sample outside the allowed band.",
  "Starts the low-priority signal without waiting for confirmation (ADR-0030). A compile-time check holds sample + conversion + alarm cycle ≤ 5 s.",
  "Test: unit tests of limit_evaluator, including the budget test.",
  [(E, 24)], [(TE, "test_first_out_sample_raises_the_early_alarm"), (TE, "test_early_alarm_budget_fits_5_s")]),
 ("MRTM-EXI-002", ["MRTM-ALM-002"], "Excursion item confirmation",
  "The excursion item shall report the confirmed excursion at the 31st consecutive valid sample outside the allowed band.",
  "The 31-sample count is a constant (MRTM_CONFIRM_SAMPLES) that the budget test ties to the 60 s span.",
  "Test: unit tests of limit_evaluator, including the budget test.",
  [(E, 24)], [(TE, "test_nth_consecutive_out_sample_confirms"), (TE, "test_early_alarm_budget_fits_5_s")]),
 ("MRTM-EXI-003", ["MRTM-ALM-007"], "Excursion item end",
  "The excursion item shall report the excursion end at the 31st consecutive valid sample inside the allowed band.",
  "Same count as confirmation, so an excursion needs 60 s of good air to end.",
  "Test: unit tests of limit_evaluator.",
  [(E, 24)], [(TE, "test_nth_consecutive_in_sample_ends_excursion")]),
 ("MRTM-ALI-001", ["MRTM-ALM-001"], "Alarm item early light",
  "The alarm item shall flash the red indicator at 1 Hz within one 1 s alarm cycle of the early excursion report.",
  "The visual half of the early tier (ADR-0030). Colour and rate differ from IEC 60601-1-8 low priority (delta D-1; assumption A-42).",
  "Test: unit tests of alarm_mgr.",
  [(A, 77)], [(TA, "test_early_alarm_is_red_1_hz_without_buzzer_then_escalates")]),
 ("MRTM-ALI-002", ["MRTM-ALM-003"], "Alarm item buzzer on",
  "The alarm item shall switch the buzzer drive on within one 1 s alarm cycle of the confirmed excursion report.",
  "The software share of ALM-003; the alarm task runs every 1 s (ADR-0019).",
  "Test: unit tests of alarm_mgr.",
  [(A, 113)], [(TA, "test_confirm_sounds_the_buzzer_and_flashes_red_at_2_hz")]),
 ("MRTM-ALI-003", ["MRTM-ALM-004"], "Alarm item buzzer off",
  "The alarm item shall switch the buzzer drive off within one 1 s alarm cycle of a debounced acknowledge press.",
  "The button is read with a 50 ms debounce inside the alarm item (IFC-002).",
  "Test: unit tests of alarm_mgr.",
  [(A, 163)], [(TA, "test_ack_stops_the_buzzer_in_the_same_step_and_logs"), (TA, "test_button_debounce_50_ms")]),
 ("MRTM-ALI-004", ["MRTM-ALM-005"], "Alarm item heartbeat",
  "The alarm item shall advance its heartbeat counter in every 1 s alarm cycle.",
  "The supervisor item stops the watchdog pulses when this counter stops (SVI-001), which lets the backup alarm sound.",
  "Test: unit tests of alarm_mgr.",
  [(A, 174)], [(TA, "test_heartbeat_moves_on_every_step")]),
 ("MRTM-BZR-001", ["MRTM-ALM-003", "MRTM-ALM-005"], "Buzzer loudness",
  "The buzzer shall produce a sound pressure level of 65 dB(A) or more at 1 m when either drive input is active.",
  "One sounder, two OR-ed drive inputs: the firmware and the backup alarm (ADR-0017). 65 dB(A) is a synthetic figure (A-40).",
  "Test: SP-06 sound level meter at 1 m.", [], ["SP-06"]),
 ("MRTM-IND-001", ["MRTM-ALM-001"], "Red indicator response",
  "The red indicator shall follow its drive input within 10 ms.",
  "A flash pattern is only as good as the lamp that shows it; 10 ms is small against a 250 ms half-period.",
  "Test: SP-01 oscilloscope on the drive and a light sensor.", [], ["SP-01"]),
 ("MRTM-IND-002", ["MRTM-ALM-004"], "Acknowledge button contact",
  "The acknowledge button shall close its contact for as long as it is pressed.",
  "A momentary contact; the alarm item debounces it (ALI-003).",
  "Inspection of the part; SP-01 acknowledge step.", [], ["SP-01"]),
 # ---------------- backup-alarm (assembly: one more black/white-box step) ----------------
 ("MRTM-BKA-001", ["MRTM-ALM-005"], "Backup alarm timeout",
  "The backup alarm shall drive the buzzer within 10 s of the last watchdog service pulse.",
  "The alarm subsystem's backup path, owned by one assembly that needs no processor (ADR-0013).",
  "Test: SP-03.", [], ["SP-03"]),
 ("MRTM-BKA-002", ["MRTM-ALM-008"], "Backup alarm hold-up",
  "The backup alarm shall drive the buzzer for 60 s or more after the loss of both mains and battery power.",
  "Its own stored energy; nothing else in the monitor is powered then.",
  "Test: SP-03.", [], ["SP-03"]),
 ("MRTM-BKT-001", ["MRTM-BKA-001"], "Backup timer period",
  "The backup timer shall assert its timeout output 9 s ± 0.9 s after the last service pulse.",
  "9.9 s worst case stays inside the 10 s of BKA-001; the tolerance is a synthetic part-class figure (A-40).",
  "Test: SP-03 with the pulses stopped.", [], ["SP-03"]),
 ("MRTM-BKD-001", ["MRTM-BKA-001"], "Backup driver response",
  "The backup driver shall drive the buzzer backup input within 100 ms of the timeout output.",
  "A transistor stage; 100 ms keeps the sum under 10 s with the timer's 9.9 s.",
  "Test: SP-03 oscilloscope.", [], ["SP-03"]),
 ("MRTM-BKH-001", ["MRTM-BKA-002"], "Hold-up energy",
  "The hold-up store shall supply the backup timer and the backup driver for 60 s or more after all power is lost.",
  "Sized in 09-hardware/power-budget.md (133 s computed).",
  "Test: SP-03 with both supplies removed.", [], ["SP-03"]),
 # ---------------- display (subsystem) ----------------
 ("MRTM-DSP-001", ["MRTM-SYS-005", "MRTM-SYS-007"], "Display excursion warning",
  "The display subsystem shall show the excursion warning within 1 s of excursion confirmation until the excursion ends.",
  "The display share of the 5 s of SYS-005.",
  "Test: unit tests of the display item; integration INT-01.", [], [(TI, "test_int01_excursion_chain")]),
 ("MRTM-DSP-002", ["MRTM-SYS-011", "MRTM-PRF-004", "MRTM-IFC-004"], "Display temperature",
  "The display subsystem shall show the current temperature at 0.1 °C resolution in digits of 5 mm or more, refreshed every 10 s.",
  "Readable from the fridge door; 10 s refresh avoids flicker of the last digit.",
  "Test: SP-09.", [], ["SP-09"]),
 ("MRTM-DSP-003", ["MRTM-SYS-013", "MRTM-SAF-012", "MRTM-SAF-016", "MRTM-SYS-022"], "Display messages",
  "The display subsystem shall show the probe fault, calibration due, band limits and log capacity messages within 1 s of their cause.",
  "Two of these messages are risk controls with no other signal (SAF-012 HAZ-004, SAF-016 HAZ-007) — why this subsystem stays class C (ADR-0034).",
  "Test: unit tests of the display item; SP-05; SP-09.", [], ["SP-05", "SP-09"]),
 ("MRTM-OLD-001", ["MRTM-DSP-002"], "Panel digit height",
  "The display panel shall draw the temperature digits at a character height of 5 mm or more.",
  "Panel size and font chosen in ADR-0016.",
  "Inspection: SP-09 ruler on the panel.", [], ["SP-09"]),
 ("MRTM-DSI-001", ["MRTM-DSP-001", "MRTM-DSP-003"], "Display item redraw",
  "The display item shall redraw the frame within 1 s of a state change message.",
  "The display task runs every 1 s (ADR-0019).",
  "Test: unit tests of display_mgr.",
  [("mrtm_app/src/mrtm_app.c", 138)],
  [("firmware/components/display_mgr/test/test_display_mgr.c", "test_excursion_warning_for_the_whole_excursion"),
   ("firmware/components/display_mgr/test/test_display_mgr.c", "test_probe_fault_message"),
   ("firmware/components/display_mgr/test/test_display_mgr.c", "test_calibration_due_and_log_capacity_messages")]),
 ("MRTM-DSI-002", ["MRTM-DSP-002"], "Display item number rate",
  "The display item shall change the displayed temperature at most once per 10 s, at 0.1 °C resolution.",
  "Carries DSP-002's refresh down to the software.",
  "Test: unit tests of display_mgr.",
  [("mrtm_app/src/mrtm_app.c", 119)],
  [("firmware/components/display_mgr/test/test_display_mgr.c", "test_temperature_refreshes_every_10_s_in_tenths")]),
 # ---------------- logging-and-history (subsystem) ----------------
 ("MRTM-LOG-001", ["MRTM-SAF-018", "MRTM-SYS-008", "MRTM-SYS-009", "MRTM-SYS-010"], "Logging record write",
  "The logging subsystem shall store each event record in 2 separate flash sectors within 1 s of the event.",
  "Two copies survive one bad sector (HAZ-008).",
  "Test: unit tests of the log item; SP-07.", [], ["SP-07"]),
 ("MRTM-LOG-002", ["MRTM-SYS-015"], "Logging retention",
  "The logging subsystem shall retain the newest 10000 event records.",
  "10 000 records is assumption A-04 (about 2 years of events); " + SRC_WHO + ".",
  "Test: unit tests of the log item; SP-07.", [], ["SP-07"]),
 ("MRTM-LOG-003", ["MRTM-SYS-014", "MRTM-IFC-003", "MRTM-PRF-003"], "Logging read-only export",
  "The logging subsystem shall give the USB host read-only access to the event records within 30 s of connection.",
  "The history for audit (STK-005) must not be changeable from outside (STK-006).",
  "Test: SP-08.", [], ["SP-08"]),
 ("MRTM-LOG-004", ["MRTM-SYS-020", "MRTM-SYS-008", "MRTM-SAF-022"], "Logging time stamp",
  "The logging subsystem shall time-stamp each record with UTC at 1 s resolution with a drift of 2 s per day or less.",
  "2 s per day is assumption A-14; " + SRC_WHO + ".",
  "Test: SP-12.", [], ["SP-12"]),
 ("MRTM-RTC-001", ["MRTM-LOG-004"], "Clock drift",
  "The real-time clock shall keep time with a drift of 2 s per day or less from 10 °C to 35 °C.",
  "A temperature-compensated clock part (ADR-0016); synthetic figure (A-40).",
  "Test: SP-12.", [], ["SP-12"]),
 ("MRTM-LGI-001", ["MRTM-LOG-001"], "Log item two copies",
  "The log item shall write each record with its CRC-32 to 2 separate flash sectors within 1 s of the event.",
  "The log task runs every 1 s (ADR-0019).",
  "Test: unit tests of event_log and history_ring.",
  [(L, 45)], [("firmware/components/history_ring/test/test_history_ring.c", "test_append_writes_copy_a_and_copy_b")]),
 ("MRTM-LGI-002", ["MRTM-LOG-002"], "Log item ring",
  "The log item shall keep the newest 10000 records and overwrite the oldest record when full.",
  "A ring: the log never stops accepting events (HAZ-008).",
  "Test: unit tests of history_ring.",
  [("history_ring/src/history_ring.c", 23)], [("firmware/components/history_ring/test/test_history_ring.c", "test_retains_10000_records_after_wrapping")]),
 ("MRTM-USI-001", ["MRTM-LOG-003"], "USB item volume",
  "The USB item shall present the event log as a read-only mass-storage volume within 30 s of connection.",
  "Any computer can read it without a driver (ADR-0011).",
  "Test: unit tests of usb_export; SP-08.",
  [(U, 77)], [("firmware/components/usb_export/test/test_usb_export.c", "test_history_csv_is_marked_read_only")]),
 ("MRTM-USI-002", ["MRTM-LOG-003"], "USB item read-only access",
  "The USB item shall refuse every write request from the USB host.",
  "The segregation argument of this class B item rests on it (ADR-0034): the USB item cannot change the log.",
  "Test: unit tests of usb_export.",
  [(U, 96)], [("firmware/components/usb_export/test/test_usb_export.c", "test_every_write_is_refused")]),
 # ---------------- power (subsystem) ----------------
 ("MRTM-PWR-001", ["MRTM-SYS-016"], "Power switch-over",
  "The power subsystem shall switch the load to the battery within 100 ms of mains power loss.",
  "Shorter than the hold-up of the processor supply, so the firmware never resets on a mains cut.",
  "Test: SP-04 oscilloscope.", [], ["SP-04"]),
 ("MRTM-PWR-002", ["MRTM-ENV-001"], "Power battery time",
  "The power subsystem shall supply the monitor from the battery for 4 h.",
  "4 h is the mains-loss need of STK-008 (assumption A-11).",
  "Test: SP-04.", [], ["SP-04"]),
 ("MRTM-PWR-003", ["MRTM-SAF-005", "MRTM-SAF-008", "MRTM-SYS-023"], "Power events",
  "The power subsystem shall report mains loss, mains restore and battery voltage below 3.4 V within 1 s.",
  "Feeds the log (SAF-005) and the low-battery alarm (SAF-008).",
  "Test: unit tests of the power item; integration INT-05.", [], [(TI, "test_int05_power_loss_logged_within_1_s")]),
 ("MRTM-BAT-001", ["MRTM-PWR-002"], "Battery capacity",
  "The battery shall store 2000 mAh or more at 3.7 V nominal.",
  "Gives 49 h computed against the 4 h need (09-hardware/power-budget.md); synthetic part (A-40).",
  "Inspection of the part; SP-04.", [], ["SP-04"]),
 ("MRTM-PPT-001", ["MRTM-PWR-001"], "Power path switch",
  "The power path shall switch the load from mains to battery within 100 ms.",
  "A diode-OR power path; no firmware in the loop.",
  "Test: SP-04.", [], ["SP-04"]),
 ("MRTM-PWI-001", ["MRTM-PWR-003"], "Power item mains events",
  "The power item shall post the mains-lost and mains-restored signals within 1 s of the mains sense edge.",
  "The power item reads the sense input every 1 s cycle.",
  "Test: unit tests of power_mon.",
  [("power_mon/src/power_mon.c", 21)], [("firmware/components/power_mon/test/test_power_mon.c", "test_mains_loss_and_restore_are_logged_from_the_edge")]),
 ("MRTM-PWI-002", ["MRTM-PWR-003"], "Power item battery low",
  "The power item shall post the battery-low signal after 2 consecutive battery readings below 3.4 V.",
  "Two readings filter one noisy conversion; 2 s stays inside the 5 s of SAF-008.",
  "Test: unit tests of power_mon.",
  [("power_mon/src/power_mon.c", 31)], [("firmware/components/power_mon/test/test_power_mon.c", "test_battery_below_3400_mv_twice_sounds_the_buzzer")]),
 # ---------------- supervision (subsystem) ----------------
 ("MRTM-SUP-001", ["MRTM-SAF-004", "MRTM-SAF-006"], "Supervision restart",
  "The supervision subsystem shall restart the monitoring software within 2 s of a software watchdog timeout.",
  "Risk control of HAZ-003 (firmware hang).",
  "Test: SP-03.", [], ["SP-03"]),
 ("MRTM-SUP-002", ["MRTM-SAF-007", "MRTM-SAF-023"], "Supervision power-up tests",
  "The supervision subsystem shall test the buzzer within 5 s and the backup alarm within 15 s of power-up.",
  "A silent alarm path must be found at power-up, not at the next excursion (HAZ-006).",
  "Test: unit tests of the supervisor item; SP-05.", [], ["SP-05"]),
 ("MRTM-SUP-003", ["MRTM-SAF-017", "MRTM-SYS-017"], "Supervision band check",
  "The supervision subsystem shall refuse a stored allowed band that fails its CRC-32 check.",
  "No band is better than a wrong band: the monitor goes fail-safe and sounds (HAZ-007).",
  "Test: integration INT-03.", [], [(TI, "test_int03_corrupt_config_fail_safe")]),
 ("MRTM-SUP-004", ["MRTM-SAF-010"], "Supervision pulse stop",
  "The supervision subsystem shall stop the watchdog service pulses within 2 s of the alarm item missing its 1 s cycle.",
  "Hands a stuck alarm item to the backup alarm (ALM-005).",
  "Test: integration INT-02.", [], [(TI, "test_int02_watchdog_chain")]),
 ("MRTM-MCU-001", ["MRTM-SUP-001"], "Processor watchdog reset",
  "The microcontroller shall reset within 1 s of its hardware watchdog expiry.",
  "The processor's own watchdog is the last software-independent restart (ADR-0018).",
  "Test: SP-03.", [], ["SP-03"]),
 ("MRTM-SVI-001", ["MRTM-SUP-004", "MRTM-SUP-001"], "Supervisor item pulses",
  "The supervisor item shall stop the watchdog service pulses within 2 s of a missed alarm heartbeat.",
  "The software half of the backup chain (SAF-010).",
  "Test: unit tests of wdt_kicker.",
  [("wdt_kicker/src/wdt_kicker.c", 18)], [("firmware/components/wdt_kicker/test/test_wdt_kicker.c", "test_pulses_stop_within_2_s_of_a_missed_alarm_cycle")]),
 ("MRTM-SVI-002", ["MRTM-SUP-002"], "Supervisor item self-tests",
  "The supervisor item shall run the buzzer test within 5 s and the backup alarm test within 15 s of power-up.",
  "Both windows counted from t = 0 (ADR-0014).",
  "Test: unit tests of diagnostics.",
  [("diagnostics/src/diagnostics.c", 13)], [("firmware/components/diagnostics/test/test_diagnostics.c", "test_power_up_tests_pass_inside_their_windows")]),
 ("MRTM-SVI-003", ["MRTM-SUP-003"], "Supervisor item band load",
  "The supervisor item shall load the allowed band only when its CRC-32 check passes.",
  "No default band exists in firmware (ADR-0024).",
  "Test: unit tests of config_mgr.",
  [("config_mgr/src/config_mgr.c", 19)], [("firmware/components/config_mgr/test/test_config_mgr.c", "test_bad_crc_is_refused_with_err_crc")]),
]
