# Phase 8 design data: one source for the SysML contracts, the contracts.md files and the dictionary terms.
ERRORS = [  # (sysml, C, value, meaning)
 ("ok","MRTM_OK",0,"Done, nothing wrong."),
 ("errArg","MRTM_ERR_ARG",1,"A caller passed a bad argument (NULL pointer, value out of range)."),
 ("errTimeout","MRTM_ERR_TIMEOUT",2,"A bus or queue did not answer in time."),
 ("errCrc","MRTM_ERR_CRC",3,"A checksum did not match (probe scratchpad, log record, stored config)."),
 ("errRange","MRTM_ERR_RANGE",4,"A reading is outside what the part can physically report (-30..50 degC)."),
 ("errBus","MRTM_ERR_BUS",5,"A 1-Wire or I2C transaction failed."),
 ("errFlash","MRTM_ERR_FLASH",6,"A flash erase or write failed."),
 ("errNvs","MRTM_ERR_NVS",7,"The stored configuration is missing or unreadable."),
 ("errFull","MRTM_ERR_FULL",8,"A queue is full; the item was not taken."),
 ("errState","MRTM_ERR_STATE",9,"Called in the wrong mode (for example before init)."),
 ("errHw","MRTM_ERR_HW",10,"A hardware self-test failed (buzzer current, backup alarm, RTC)."),
]
EVENTS = [  # (sysml, C, value, meaning, requirement)
 ("excursionStart","MRTM_EV_EXCURSION_START",1,"An excursion was confirmed.","MRTM-SYS-008"),
 ("excursionEnd","MRTM_EV_EXCURSION_END",2,"An excursion ended; the record carries the peak.","MRTM-SYS-009"),
 ("acknowledged","MRTM_EV_ACK",3,"Staff pressed the acknowledge button during an alarm.","MRTM-SYS-010"),
 ("powerLoss","MRTM_EV_POWER_LOSS",4,"Mains power was lost.","MRTM-SAF-005"),
 ("powerRestore","MRTM_EV_POWER_RESTORE",5,"Mains power came back.","MRTM-SYS-023"),
 ("probeFault","MRTM_EV_PROBE_FAULT",6,"The probe fault was declared.","MRTM-SYS-012"),
 ("probeRecovered","MRTM_EV_PROBE_RECOVERED",7,"Good samples arrived again after a probe fault.","MRTM-SYS-012"),
 ("buzzerFault","MRTM_EV_BUZZER_FAULT",8,"The buzzer drew too little current while driven.","MRTM-SAF-014"),
 ("buttonFault","MRTM_EV_BUTTON_FAULT",9,"The acknowledge button stayed pressed for 60 s.","MRTM-SAF-019"),
 ("clockFault","MRTM_EV_CLOCK_FAULT",10,"The RTC reported an oscillator stop at power-up.","MRTM-SAF-022"),
 ("configCrcFault","MRTM_EV_CONFIG_CRC_FAULT",11,"The stored allowed band failed its CRC-32 check.","MRTM-SAF-017"),
 ("selfTestPass","MRTM_EV_SELF_TEST_PASS",12,"All power-up tests passed.","MRTM-SAF-007"),
 ("selfTestFail","MRTM_EV_SELF_TEST_FAIL",13,"A power-up test failed; the record's value says which.","MRTM-SAF-023"),
 ("lowBattery","MRTM_EV_LOW_BATTERY",14,"The battery fell below 3.4 V.","MRTM-SAF-008"),
 ("watchdogRestart","MRTM_EV_WATCHDOG_RESTART",15,"The firmware restarted after a software watchdog timeout.","MRTM-SAF-004"),
 ("logRecordCorrupt","MRTM_EV_LOG_RECORD_CORRUPT",16,"A log record failed its CRC-32 when read.","MRTM-SYS-021"),
 ("logCapacityWarning","MRTM_EV_LOG_CAPACITY_WARNING",17,"The log reached 9000 records.","MRTM-SYS-022"),
 ("configChanged","MRTM_EV_CONFIG_CHANGED",18,"A technician stored a new configuration.","MRTM-SAF-017"),
 ("i2cBusReset","MRTM_EV_I2C_BUS_RESET",19,"The I2C bus was reset after a timeout.","MRTM-SAF-021"),
 ("realarm","MRTM_EV_REALARM",20,"The buzzer sounded again 15 min after an acknowledgement.","MRTM-SYS-019"),
]
# Module: id (component), folder, language, one-line purpose, requirements, types (C), functions.
# function: (sysml name, C signature, [(dir, name, SysML type)], pre, post, errors, algorithm or "")
MODULES = [
 ("sensorSampler","sensor_sampler","C","Read the probe, check it, and say when it has failed.",
  ["MRTM-SYS-001","MRTM-SYS-012","MRTM-SAF-003","MRTM-IFC-001","MRTM-PRF-001"],
  ["typedef struct { int16_t tenths; uint32_t utc_s; bool valid; } mrtm_sample_t;  /* valid = CRC ok AND -30..50 degC */"],
  [("sensor_sampler_init","mrtm_err_t sensor_sampler_init(const mrtm_config_t *cfg);",[("in","cfg","MonitorConfig"),("out","ret","ErrorCode")],
    "cfg != NULL, config CRC already checked.","Bus reset done, first conversion started.","MRTM_ERR_ARG, MRTM_ERR_BUS",""),
   ("sensor_sampler_read","mrtm_err_t sensor_sampler_read(uint32_t now_s, mrtm_sample_t *out);",[("in","nowS","Natural"),("out","sample","TemperatureSample"),("out","ret","ErrorCode")],
    "Called by sensorTask every MRTM_SAMPLE_PERIOD_MS (10 s).","out->valid is false on CRC or range failure; tenths = raw/1.6 + probe offset, rounded to 0.1 degC.",
    "MRTM_ERR_BUS, MRTM_ERR_CRC, MRTM_ERR_RANGE",
    "Read 9-byte scratchpad; CRC-8 (Dallas/Maxim, poly 0x31) over bytes 0..7 must equal byte 8; raw 12-bit two's complement / 16 = degC; outside -30..50 degC -> RANGE (MRTM-SAF-003, declares probe fault at once); start the next 750 ms conversion."),
   ("sensor_sampler_probe_fault","bool sensor_sampler_probe_fault(uint32_t now_s);",[("in","nowS","Natural"),("out","fault","Boolean")],
    "none","true when the last valid sample is 30 s old or older (MRTM_PROBE_FAULT_S), or the last reading was out of range.","none",
    "fault = (now_s - last_valid_s >= 30) OR last_out_of_range. Clears on the next valid sample (event PROBE_RECOVERED).")]),
 ("limitEvaluator","limit_evaluator","C","Decide when an excursion starts and ends.",
  ["MRTM-SYS-002","MRTM-SYS-017","MRTM-SYS-018"],
  ["typedef enum { LIMIT_NONE = 0, LIMIT_CONFIRMED, LIMIT_ENDED } limit_event_t;",
   "typedef struct { int16_t low, high, hyst; uint8_t out_run, in_run; bool excursion; int16_t peak; } limit_eval_t;"],
  [("limit_evaluator_init","void limit_evaluator_init(limit_eval_t *st, int16_t low_tenths, int16_t high_tenths);",[("in","lowTenths","Integer"),("in","highTenths","Integer")],
    "st != NULL, low < high.","No excursion, both runs 0.","none (asserts)",""),
   ("limit_evaluator_step","limit_event_t limit_evaluator_step(limit_eval_t *st, const mrtm_sample_t *s);",[("in","sample","TemperatureSample"),("out","limitEvent","Natural")],
    "Called once per sample, straight after sensor_sampler_read.","Returns LIMIT_CONFIRMED on the 7th consecutive out-of-band sample, LIMIT_ENDED on the 7th consecutive in-band sample during an excursion.","none",
    "Invalid samples are skipped: they neither count nor reset (A-29). out = t < low - hyst OR t > high + hyst while no excursion; in = low + hyst <= t <= high - hyst while in excursion; hyst = MRTM_HYSTERESIS_TENTHS = 0 (A-26). out_run counts consecutive out samples, in_run consecutive in samples; each resets the other. Confirm at out_run == MRTM_CONFIRM_SAMPLES (7 -> spans 60 s at 10 s); end at in_run == 7. Peak = max |distance outside band| sample, kept from the first out sample."),
   ("limit_evaluator_peak","int16_t limit_evaluator_peak(const limit_eval_t *st);",[("out","peakTenths","Integer")],
    "st != NULL.","The most extreme temperature of the current or last excursion, 0.1 degC.","none","")]),
 ("alarmMgr","alarm_mgr","C","Run the alarm state machine and drive the buzzer and red light.",
  ["MRTM-SYS-003","MRTM-SYS-004","MRTM-SYS-006","MRTM-SYS-019","MRTM-PRF-002","MRTM-SAF-001","MRTM-SAF-002","MRTM-SAF-006","MRTM-SAF-011","MRTM-SAF-014","MRTM-SAF-015","MRTM-SAF-019","MRTM-IFC-002"],
  ["typedef enum { ALARM_QUIET = 0, ALARM_SOUNDING, ALARM_SILENCED, ALARM_PROBE_FAULT, ALARM_BUZZER_FAULT } alarm_state_t;",
   "typedef enum { SIG_EXCURSION_CONFIRMED = 1, SIG_EXCURSION_ENDED, SIG_ACK_PRESSED, SIG_PROBE_FAULT, SIG_PROBE_RECOVERED, SIG_BATTERY_LOW } alarm_signal_t;"],
  [("alarm_mgr_init","mrtm_err_t alarm_mgr_init(void);",[("out","ret","ErrorCode")],
    "GPIO 11 (buzzer), 12 (red LED, LEDC), 16 (buzzer sense), button GPIO configured by board init.","State restored from NVS key 'alarm' (MRTM-SAF-006): an unacknowledged alarm is sounding again within 2 s of the restart.","MRTM_ERR_NVS (treated as QUIET + logged)",""),
   ("alarm_mgr_post","mrtm_err_t alarm_mgr_post(alarm_signal_t sig);",[("in","signal","Natural"),("out","ret","ErrorCode")],
    "Any task. alarm_mgr_post_from_isr() is the ISR form.","Signal queued; alarmTask woken at once (task notification), not at its next 1 s tick.","MRTM_ERR_FULL (queue depth 8; the sender logs it)",""),
   ("alarm_mgr_step","void alarm_mgr_step(uint32_t now_ms);",[("in","nowMs","Natural")],
    "alarmTask only, at least every 1000 ms and on every notification.","One transition of MrtmSwStates::AlarmStates taken per signal; outputs driven; heartbeat incremented.","none",
    "Drain the signal queue through the transition table of AlarmStates. Outputs: SOUNDING = buzzer on continuous, red LED LEDC 2 Hz 50 %; PROBE_FAULT = buzzer toggles every 1 s step (1 s on/1 s off, MRTM-SAF-011); BUZZER_FAULT = red LED 4 Hz; SILENCED = buzzer off, LED 2 Hz, re-sound when now - ack_ms >= MRTM_REALARM_MS (15 min). Buzzer current: while driven, sense GPIO low for >= 5 consecutive steps -> SIG buzzer fault (MRTM-SAF-014). Heartbeat += 1 at the end of every step (read by wdt_kicker)."),
   ("alarm_mgr_button_isr","void alarm_mgr_button_isr(void *arg);",[("in","arg","Natural")],
    "GPIO interrupt on the button line, both edges.","A press stable for 50 ms posts SIG_ACK_PRESSED (MRTM-IFC-002); held 60 s posts nothing more and logs BUTTON_FAULT (MRTM-SAF-019).","none",
    "Debounce: on an edge, (re)arm a 50 ms esp_timer one-shot; when it fires, read the pin; if still pressed and last stable state was released -> press accepted. While pressed, a 60 s one-shot is armed; if it fires the button is declared stuck and further presses are ignored until release."),
   ("alarm_mgr_heartbeat","uint32_t alarm_mgr_heartbeat(void);",[("out","beat","Natural")],"none","Current heartbeat count (atomic read).","none","")]),
 ("displayMgr","display_mgr","C++","Draw the screen. C interface outside, classes inside.",
  ["MRTM-SYS-005","MRTM-SYS-007","MRTM-SYS-011","MRTM-SYS-013","MRTM-SYS-022","MRTM-PRF-004","MRTM-IFC-004","MRTM-SAF-012","MRTM-SAF-016","MRTM-SAF-021"],
  ["typedef struct { int16_t temp_tenths; bool temp_valid; alarm_state_t alarm; bool calib_due; bool log_warn; bool show_band; int16_t band_low, band_high; } display_model_t;"],
  [("display_mgr_init","extern \"C\" mrtm_err_t display_mgr_init(void);",[("out","ret","ErrorCode")],
    "I2C master on the display bus ready.","SSD1306 initialised, screen cleared, band shown for 3 s (MRTM-SAF-016).","MRTM_ERR_BUS",""),
   ("display_mgr_update","extern \"C\" void display_mgr_update(const display_model_t *m);",[("in","model","DisplayFrame")],
    "Any task; copies the model under a mutex.","Next tick draws the new model.","none",""),
   ("display_mgr_tick","extern \"C\" void display_mgr_tick(void);",[],
    "displayTask every 500 ms.","Dirty widgets redrawn and the frame sent; a stuck bus is reset within 1 s (MRTM-SAF-021).","none (bus errors are logged as I2C_BUS_RESET)",
    "Screen::render(): for each widget, if dirty, draw into the 1024-byte frame buffer; send the changed pages over I2C with a 100 ms transaction timeout; on timeout: clock 9 pulses on SCL, re-init the SSD1306, log I2C_BUS_RESET, total <= 1 s. Temperature refreshed every 10 s (MRTM-PRF-004) from the model; digits 32 px tall = 5.1 mm on the 0.96 in panel (MRTM-IFC-004).")]),
 ("eventLog","event_log","C","Turn events into stamped records and store each twice.",
  ["MRTM-SYS-008","MRTM-SYS-009","MRTM-SYS-010","MRTM-SYS-023","MRTM-SAF-018"],
  ["typedef struct __attribute__((packed)) { uint32_t seq; uint32_t utc_s; uint8_t kind; uint8_t rsv; int16_t tenths; int16_t peak_tenths; uint8_t pad[14]; uint32_t crc32; } event_record_t;  /* 32 bytes */"],
  [("event_log_post","mrtm_err_t event_log_post(mrtm_event_kind_t kind, int16_t tenths, int16_t peak_tenths);",[("in","kind","EventKind"),("in","tenths","Integer"),("in","peakTenths","Integer"),("out","ret","ErrorCode")],
    "Any task; event_log_post_from_isr() is the ISR form.","Record queued with the UTC second of the call (time-stamping at the event, not at the write).","MRTM_ERR_FULL (queue depth 32)",
    "utc_s = rtc_clock_now() taken at post time (1 s resolution, MRTM-SYS-008/010/023)."),
   ("event_log_step","void event_log_step(uint32_t timeout_ms);",[("in","timeoutMs","Natural")],
    "logTask only.","Every queued record has seq, CRC-32 and is written to copy A then copy B within 1 s of its event (MRTM-SAF-018).","MRTM_ERR_FLASH (retried once, then logged as SELF_TEST_FAIL value 'flash')",
    "Take one record; seq = ++last_seq; crc32 = CRC-32/ISO-HDLC over bytes 0..27; history_ring_append().")]),
 ("historyRing","history_ring","C","Keep 10000 records in a ring over two mirrored flash areas.",
  ["MRTM-SYS-015","MRTM-SYS-021","MRTM-SYS-022"],
  ["typedef struct { uint32_t head_seq; uint32_t count; } history_ring_t;"],
  [("history_ring_init","mrtm_err_t history_ring_init(history_ring_t *r);",[("out","ring","HistoryRing"),("out","ret","ErrorCode")],
    "Partitions 'logA' and 'logB' present.","head_seq = highest seq with a valid CRC in either copy; count = min(head_seq, capacity).","MRTM_ERR_FLASH",
    "Scan both partitions slot by slot (10 112 slots each: 79 sectors x 128 slots); keep the max valid seq. Slot index = seq mod slots."),
   ("history_ring_append","mrtm_err_t history_ring_append(history_ring_t *r, const event_record_t *rec);",[("in","rec","EventRecord"),("out","ret","ErrorCode")],
    "logTask only.","Record in copy A and copy B; when count reaches 9000 the capacity-warning event is posted once (MRTM-SYS-022).","MRTM_ERR_FLASH",
    "If the slot is the first of a sector, erase that sector in A, write A, erase in B, write B (erase-ahead keeps 10 000 readable, A-21 overwrite oldest)."),
   ("history_ring_read","mrtm_err_t history_ring_read(const history_ring_t *r, uint32_t age, event_record_t *out);",[("in","age","Natural"),("out","rec","EventRecord"),("out","ret","ErrorCode")],
    "age < count (0 = newest).","out holds a record whose CRC-32 matches, from copy A or else copy B.","MRTM_ERR_CRC when both copies fail — posts LOG_RECORD_CORRUPT within 1 s (MRTM-SYS-021)",""),
   ("history_ring_count","uint32_t history_ring_count(const history_ring_t *r);",[("out","n","Natural")],"none","Records held, 0..10000.","none","")]),
 ("rtcClock","rtc_clock","C","Give UTC seconds and report a stopped oscillator.",
  ["MRTM-SYS-020","MRTM-SAF-022"],[],
  [("rtc_clock_init","mrtm_err_t rtc_clock_init(bool *osc_stopped);",[("out","oscStopped","Boolean"),("out","ret","ErrorCode")],
    "I2C bus ready.","*osc_stopped = the RTC's oscillator-stop flag; flag cleared after it is read; CLOCK_FAULT logged within 2 s of power-up when set (MRTM-SAF-022).","MRTM_ERR_BUS",""),
   ("rtc_clock_now","uint32_t rtc_clock_now(void);",[("out","utcS","Natural")],
    "Any task.","UTC seconds, from a copy refreshed once per second by an esp_timer from the RTC (no I2C in the caller's path).","none",""),
   ("rtc_clock_set","mrtm_err_t rtc_clock_set(uint32_t utc_s);",[("in","utcS","Natural"),("out","ret","ErrorCode")],
    "Technician command over USB (A-23).","RTC set; CONFIG_CHANGED logged.","MRTM_ERR_BUS, MRTM_ERR_ARG","")]),
 ("configMgr","config_mgr","C","Load and check the technician values.",
  ["MRTM-SAF-017"],
  ["typedef struct { uint16_t version; int16_t band_low_tenths, band_high_tenths, probe_offset_tenths; uint32_t calibration_utc; uint32_t crc32; } mrtm_config_t;"],
  [("config_mgr_load","mrtm_err_t config_mgr_load(mrtm_config_t *out);",[("out","config","MonitorConfig"),("out","ret","ErrorCode")],
    "NVS initialised.","out valid only when MRTM_OK. There is NO default band in firmware: a missing or bad record means failSafe with the buzzer on within 5 s (MRTM-SAF-017).","MRTM_ERR_NVS, MRTM_ERR_CRC",
    "Read NVS blob 'cfg'; CRC-32 over all bytes before crc32 must match; band must satisfy MRTM_BAND_MIN_TENTHS <= low < high <= MRTM_BAND_MAX_TENTHS."),
   ("config_mgr_store","mrtm_err_t config_mgr_store(const mrtm_config_t *in);",[("in","config","MonitorConfig"),("out","ret","ErrorCode")],
    "Technician command over USB (Q-15).","Stored with a fresh CRC; CONFIG_CHANGED logged; takes effect at the next restart.","MRTM_ERR_ARG, MRTM_ERR_NVS","")]),
 ("wdtKicker","wdt_kicker","C","Pulse the outside watchdog only while the alarm task is alive.",
  ["MRTM-SAF-004","MRTM-SAF-009","MRTM-SAF-010"],[],
  [("wdt_kicker_init","void wdt_kicker_init(void);",[],
    "GPIO 15 output.","ESP-IDF task watchdog armed at MRTM_TASK_WDT_S (5 s) for alarmTask and supervisorTask, panic-restart on timeout (restart < 2 s, MRTM-SAF-004).","none",""),
   ("wdt_kicker_step","void wdt_kicker_step(uint32_t now_ms, uint32_t alarm_beat);",[("in","nowMs","Natural"),("in","alarmBeat","Natural")],
    "supervisorTask every 500 ms.","A pulse on GPIO 15 only if alarm_beat changed within the last MRTM_HEARTBEAT_MAX_MS (2000 ms); otherwise no pulse, so the backup alarm sounds within 10 s (MRTM-SAF-009/010).","none",
    "if (alarm_beat != last_beat) { last_beat = alarm_beat; last_change = now_ms; } if (now_ms - last_change <= 2000) pulse 1 ms high on GPIO 15.")]),
 ("diagnostics","diagnostics","C","Run the power-up tests and the running checks.",
  ["MRTM-SAF-007","MRTM-SAF-023"],
  ["typedef struct { bool buzzer_ok, backup_ok, config_ok, clock_ok; } diag_result_t;"],
  [("diagnostics_power_up","mrtm_err_t diagnostics_power_up(diag_result_t *out);",[("out","ret","ErrorCode")],
    "Before monitoring starts (SystemModes::selfTest).","Within 5 s: buzzer driven 200 ms and current seen (MRTM-SAF-007); within 15 s: pulses held back 12 s and the backup alarm's sense seen, then pulses resumed (MRTM-SAF-023); result logged as SELF_TEST_PASS or SELF_TEST_FAIL.","MRTM_ERR_HW",""),
   ("diagnostics_step","void diagnostics_step(uint32_t now_ms);",[("in","nowMs","Natural")],
    "supervisorTask every 500 ms.","Hourly: task stack high-water marks logged (Phase 10 evidence).","none","")]),
 ("powerMon","power_mon","C","Watch mains and battery; log and alarm.",
  ["MRTM-SAF-005","MRTM-SAF-008","MRTM-SYS-016"],[],
  [("power_mon_init","mrtm_err_t power_mon_init(void);",[("out","ret","ErrorCode")],
    "Mains-sense GPIO input, battery ADC channel configured.","Interrupt on both edges of mains-sense.","none",""),
   ("power_mon_isr","void power_mon_isr(void *arg);",[("in","arg","Natural")],
    "Mains-sense edge.","POWER_LOSS or POWER_RESTORE posted from the ISR (logged within 1 s, MRTM-SAF-005).","none",""),
   ("power_mon_step","void power_mon_step(uint32_t now_ms);",[("in","nowMs","Natural")],
    "supervisorTask every 500 ms.","Battery below MRTM_BATTERY_LOW_MV (3400 mV) on 2 consecutive reads -> SIG_BATTERY_LOW + LOW_BATTERY event (buzzer <= 5 s, MRTM-SAF-008).","none",
    "Average 8 ADC samples, calibrated with esp_adc_cal; the divider ratio is EE-REVIEW.")]),
 ("usbExport","usb_export","C","Show the history as a read-only USB drive.",
  ["MRTM-SYS-014","MRTM-IFC-003","MRTM-PRF-003"],[],
  [("usb_export_init","mrtm_err_t usb_export_init(void);",[("out","ret","ErrorCode")],
    "TinyUSB (SOUP-5) installed.","MSC device with one FAT12 volume, one file HISTORY.CSV, write-protect bit set (MRTM-SYS-014).","MRTM_ERR_HW",""),
   ("usb_export_read10","int32_t usb_export_read10(uint32_t lba, uint32_t offset, void *buf, uint32_t size);",[("in","lba","Natural"),("out","bytes","Integer")],
    "TinyUSB callback.","Boot sector, FAT and directory are fixed tables; data sectors are CSV lines rendered on demand from history_ring_read (newest last). 10 000 records x 48 bytes = 480 kB, well inside 30 s at full speed (MRTM-PRF-003).","returns -1 on a record read error (the line is written as 'CORRUPT' instead)",""),
   ("usb_export_write10","int32_t usb_export_write10(uint32_t lba, uint32_t offset, const void *buf, uint32_t size);",[("in","lba","Natural"),("out","bytes","Integer")],
    "TinyUSB callback.","Always refuses (returns -1): the volume is read-only (MRTM-IFC-003).","none","")]),
]
